/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ddmr_constr_h_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {22, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {203, 1, 1};
static const casadi_int casadi_s4[3] = {72, 1, 1};

/* ddmr_constr_h_fun:(i0[7],i1[22],i2[0],i3[203])->(o0[72]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29, a30, a31, a32, a33, a34, a35;
  casadi_real a36, a37, a38, a39, a40, a41, a42, a43, a44, a45, a46, a47;
  casadi_real a48, a49, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59;
  casadi_real a60, a61, a62, a63, a64;
  a00=arg[0]? arg[0][3] : 0;
  a01=2.9999999999999999e-01;
  a02=arg[0]? arg[0][4] : 0;
  a02=(a01*a02);
  a03=(a00-a02);
  if (res[0]!=0) res[0][0]=a03;
  a00=(a00+a02);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[0]? arg[0][5] : 0;
  a02=arg[0]? arg[0][6] : 0;
  a01=(a01*a02);
  a02=(a00-a01);
  if (res[0]!=0) res[0][2]=a02;
  a00=(a00+a01);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[3]? arg[3][2] : 0;
  a01=arg[0]? arg[0][1] : 0;
  a02=arg[3]? arg[3][1] : 0;
  a02=(a01-a02);
  a00=(a00*a02);
  a02=arg[3]? arg[3][3] : 0;
  a03=arg[0]? arg[0][0] : 0;
  a04=arg[3]? arg[3][0] : 0;
  a04=(a03-a04);
  a02=(a02*a04);
  a00=(a00-a02);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[3]? arg[3][6] : 0;
  a02=arg[3]? arg[3][5] : 0;
  a02=(a01-a02);
  a00=(a00*a02);
  a02=arg[3]? arg[3][7] : 0;
  a04=arg[3]? arg[3][4] : 0;
  a04=(a03-a04);
  a02=(a02*a04);
  a00=(a00-a02);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[3]? arg[3][8] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][9] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][10] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[3]? arg[3][11] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][12] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][13] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[3]? arg[3][14] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][15] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][16] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[3]? arg[3][17] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][18] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][19] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[3]? arg[3][20] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][21] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][22] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[3]? arg[3][23] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][24] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][25] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[3]? arg[3][26] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][27] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][28] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][12]=a00;
  a00=arg[3]? arg[3][29] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][30] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][31] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][13]=a00;
  a00=arg[3]? arg[3][32] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][33] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][34] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][14]=a00;
  a00=arg[3]? arg[3][35] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][36] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][37] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][15]=a00;
  a00=arg[3]? arg[3][38] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][39] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][40] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][16]=a00;
  a00=arg[3]? arg[3][41] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][42] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][43] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][17]=a00;
  a00=arg[3]? arg[3][44] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][45] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][46] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][18]=a00;
  a00=arg[3]? arg[3][47] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][48] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][49] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][19]=a00;
  a00=arg[3]? arg[3][50] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][51] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][52] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][20]=a00;
  a00=arg[3]? arg[3][53] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][54] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][55] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][21]=a00;
  a00=arg[3]? arg[3][56] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][57] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][58] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][22]=a00;
  a00=arg[3]? arg[3][59] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][60] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][61] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][23]=a00;
  a00=arg[3]? arg[3][62] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][63] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][64] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][24]=a00;
  a00=arg[3]? arg[3][65] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][66] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][67] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][25]=a00;
  a00=arg[3]? arg[3][68] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][69] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][70] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][26]=a00;
  a00=arg[3]? arg[3][71] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][72] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][73] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][27]=a00;
  a00=arg[3]? arg[3][74] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][75] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][76] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][28]=a00;
  a00=arg[3]? arg[3][77] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][78] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][79] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][29]=a00;
  a00=arg[3]? arg[3][80] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][81] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][82] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][30]=a00;
  a00=arg[3]? arg[3][83] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][84] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][85] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][31]=a00;
  a00=arg[3]? arg[3][86] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][87] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][88] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][32]=a00;
  a00=arg[3]? arg[3][89] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][90] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][91] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][33]=a00;
  a00=arg[3]? arg[3][92] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][93] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][94] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][34]=a00;
  a00=arg[3]? arg[3][95] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][96] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][97] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][35]=a00;
  a00=arg[3]? arg[3][98] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][99] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][100] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][36]=a00;
  a00=arg[3]? arg[3][101] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][102] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][103] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][37]=a00;
  a00=arg[3]? arg[3][104] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][105] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][106] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][38]=a00;
  a00=arg[3]? arg[3][107] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][108] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][109] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][39]=a00;
  a00=arg[3]? arg[3][110] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][111] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][112] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][40]=a00;
  a00=arg[3]? arg[3][113] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][114] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][115] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][41]=a00;
  a00=arg[3]? arg[3][116] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][117] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][118] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][42]=a00;
  a00=arg[3]? arg[3][119] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][120] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][121] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][43]=a00;
  a00=arg[3]? arg[3][122] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][123] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][124] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][44]=a00;
  a00=arg[3]? arg[3][125] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][126] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][127] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][45]=a00;
  a00=arg[3]? arg[3][128] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][129] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][130] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][46]=a00;
  a00=arg[3]? arg[3][131] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][132] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][133] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][47]=a00;
  a00=arg[3]? arg[3][134] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][135] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][136] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][48]=a00;
  a00=arg[3]? arg[3][137] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][138] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][139] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][49]=a00;
  a00=arg[3]? arg[3][140] : 0;
  a00=(a03-a00);
  a00=casadi_sq(a00);
  a02=arg[3]? arg[3][141] : 0;
  a02=(a01-a02);
  a02=casadi_sq(a02);
  a00=(a00+a02);
  a02=arg[3]? arg[3][142] : 0;
  a00=(a00-a02);
  if (res[0]!=0) res[0][50]=a00;
  a00=arg[3]? arg[3][143] : 0;
  a02=arg[1]? arg[1][2] : 0;
  a04=(a00*a02);
  a05=arg[3]? arg[3][146] : 0;
  a06=arg[1]? arg[1][3] : 0;
  a07=(a05*a06);
  a04=(a04+a07);
  a07=arg[3]? arg[3][149] : 0;
  a08=arg[1]? arg[1][4] : 0;
  a09=(a07*a08);
  a04=(a04+a09);
  a09=arg[3]? arg[3][152] : 0;
  a10=arg[1]? arg[1][5] : 0;
  a11=(a09*a10);
  a04=(a04+a11);
  a11=arg[3]? arg[3][155] : 0;
  a12=arg[1]? arg[1][6] : 0;
  a13=(a11*a12);
  a04=(a04+a13);
  a13=arg[3]? arg[3][158] : 0;
  a14=arg[1]? arg[1][7] : 0;
  a15=(a13*a14);
  a04=(a04+a15);
  a15=arg[3]? arg[3][161] : 0;
  a16=arg[1]? arg[1][8] : 0;
  a17=(a15*a16);
  a04=(a04+a17);
  a17=arg[3]? arg[3][164] : 0;
  a18=arg[1]? arg[1][9] : 0;
  a19=(a17*a18);
  a04=(a04+a19);
  a19=arg[3]? arg[3][167] : 0;
  a20=arg[1]? arg[1][10] : 0;
  a21=(a19*a20);
  a04=(a04+a21);
  a21=arg[3]? arg[3][170] : 0;
  a22=arg[1]? arg[1][11] : 0;
  a23=(a21*a22);
  a04=(a04+a23);
  a23=arg[3]? arg[3][173] : 0;
  a24=arg[1]? arg[1][12] : 0;
  a25=(a23*a24);
  a04=(a04+a25);
  a25=arg[3]? arg[3][176] : 0;
  a26=arg[1]? arg[1][13] : 0;
  a27=(a25*a26);
  a04=(a04+a27);
  a27=arg[3]? arg[3][179] : 0;
  a28=arg[1]? arg[1][14] : 0;
  a29=(a27*a28);
  a04=(a04+a29);
  a29=arg[3]? arg[3][182] : 0;
  a30=arg[1]? arg[1][15] : 0;
  a31=(a29*a30);
  a04=(a04+a31);
  a31=arg[3]? arg[3][185] : 0;
  a32=arg[1]? arg[1][16] : 0;
  a33=(a31*a32);
  a04=(a04+a33);
  a33=arg[3]? arg[3][188] : 0;
  a34=arg[1]? arg[1][17] : 0;
  a35=(a33*a34);
  a04=(a04+a35);
  a35=arg[3]? arg[3][191] : 0;
  a36=arg[1]? arg[1][18] : 0;
  a37=(a35*a36);
  a04=(a04+a37);
  a37=arg[3]? arg[3][194] : 0;
  a38=arg[1]? arg[1][19] : 0;
  a39=(a37*a38);
  a04=(a04+a39);
  a39=arg[3]? arg[3][197] : 0;
  a40=arg[1]? arg[1][20] : 0;
  a41=(a39*a40);
  a04=(a04+a41);
  a41=arg[3]? arg[3][200] : 0;
  a42=arg[1]? arg[1][21] : 0;
  a43=(a41*a42);
  a04=(a04+a43);
  a04=casadi_sq(a04);
  a43=arg[3]? arg[3][144] : 0;
  a44=(a43*a02);
  a45=arg[3]? arg[3][147] : 0;
  a46=(a45*a06);
  a44=(a44+a46);
  a46=arg[3]? arg[3][150] : 0;
  a47=(a46*a08);
  a44=(a44+a47);
  a47=arg[3]? arg[3][153] : 0;
  a48=(a47*a10);
  a44=(a44+a48);
  a48=arg[3]? arg[3][156] : 0;
  a49=(a48*a12);
  a44=(a44+a49);
  a49=arg[3]? arg[3][159] : 0;
  a50=(a49*a14);
  a44=(a44+a50);
  a50=arg[3]? arg[3][162] : 0;
  a51=(a50*a16);
  a44=(a44+a51);
  a51=arg[3]? arg[3][165] : 0;
  a52=(a51*a18);
  a44=(a44+a52);
  a52=arg[3]? arg[3][168] : 0;
  a53=(a52*a20);
  a44=(a44+a53);
  a53=arg[3]? arg[3][171] : 0;
  a54=(a53*a22);
  a44=(a44+a54);
  a54=arg[3]? arg[3][174] : 0;
  a55=(a54*a24);
  a44=(a44+a55);
  a55=arg[3]? arg[3][177] : 0;
  a56=(a55*a26);
  a44=(a44+a56);
  a56=arg[3]? arg[3][180] : 0;
  a57=(a56*a28);
  a44=(a44+a57);
  a57=arg[3]? arg[3][183] : 0;
  a58=(a57*a30);
  a44=(a44+a58);
  a58=arg[3]? arg[3][186] : 0;
  a59=(a58*a32);
  a44=(a44+a59);
  a59=arg[3]? arg[3][189] : 0;
  a60=(a59*a34);
  a44=(a44+a60);
  a60=arg[3]? arg[3][192] : 0;
  a61=(a60*a36);
  a44=(a44+a61);
  a61=arg[3]? arg[3][195] : 0;
  a62=(a61*a38);
  a44=(a44+a62);
  a62=arg[3]? arg[3][198] : 0;
  a63=(a62*a40);
  a44=(a44+a63);
  a63=arg[3]? arg[3][201] : 0;
  a64=(a63*a42);
  a44=(a44+a64);
  a44=casadi_sq(a44);
  a04=(a04+a44);
  if (res[0]!=0) res[0][51]=a04;
  a00=(a00*a03);
  a43=(a43*a01);
  a00=(a00+a43);
  a43=arg[3]? arg[3][145] : 0;
  a00=(a00-a43);
  a00=(a00*a02);
  if (res[0]!=0) res[0][52]=a00;
  a05=(a05*a03);
  a45=(a45*a01);
  a05=(a05+a45);
  a45=arg[3]? arg[3][148] : 0;
  a05=(a05-a45);
  a05=(a05*a06);
  if (res[0]!=0) res[0][53]=a05;
  a07=(a07*a03);
  a46=(a46*a01);
  a07=(a07+a46);
  a46=arg[3]? arg[3][151] : 0;
  a07=(a07-a46);
  a07=(a07*a08);
  if (res[0]!=0) res[0][54]=a07;
  a09=(a09*a03);
  a47=(a47*a01);
  a09=(a09+a47);
  a47=arg[3]? arg[3][154] : 0;
  a09=(a09-a47);
  a09=(a09*a10);
  if (res[0]!=0) res[0][55]=a09;
  a11=(a11*a03);
  a48=(a48*a01);
  a11=(a11+a48);
  a48=arg[3]? arg[3][157] : 0;
  a11=(a11-a48);
  a11=(a11*a12);
  if (res[0]!=0) res[0][56]=a11;
  a13=(a13*a03);
  a49=(a49*a01);
  a13=(a13+a49);
  a49=arg[3]? arg[3][160] : 0;
  a13=(a13-a49);
  a13=(a13*a14);
  if (res[0]!=0) res[0][57]=a13;
  a15=(a15*a03);
  a50=(a50*a01);
  a15=(a15+a50);
  a50=arg[3]? arg[3][163] : 0;
  a15=(a15-a50);
  a15=(a15*a16);
  if (res[0]!=0) res[0][58]=a15;
  a17=(a17*a03);
  a51=(a51*a01);
  a17=(a17+a51);
  a51=arg[3]? arg[3][166] : 0;
  a17=(a17-a51);
  a17=(a17*a18);
  if (res[0]!=0) res[0][59]=a17;
  a19=(a19*a03);
  a52=(a52*a01);
  a19=(a19+a52);
  a52=arg[3]? arg[3][169] : 0;
  a19=(a19-a52);
  a19=(a19*a20);
  if (res[0]!=0) res[0][60]=a19;
  a21=(a21*a03);
  a53=(a53*a01);
  a21=(a21+a53);
  a53=arg[3]? arg[3][172] : 0;
  a21=(a21-a53);
  a21=(a21*a22);
  if (res[0]!=0) res[0][61]=a21;
  a23=(a23*a03);
  a54=(a54*a01);
  a23=(a23+a54);
  a54=arg[3]? arg[3][175] : 0;
  a23=(a23-a54);
  a23=(a23*a24);
  if (res[0]!=0) res[0][62]=a23;
  a25=(a25*a03);
  a55=(a55*a01);
  a25=(a25+a55);
  a55=arg[3]? arg[3][178] : 0;
  a25=(a25-a55);
  a25=(a25*a26);
  if (res[0]!=0) res[0][63]=a25;
  a27=(a27*a03);
  a56=(a56*a01);
  a27=(a27+a56);
  a56=arg[3]? arg[3][181] : 0;
  a27=(a27-a56);
  a27=(a27*a28);
  if (res[0]!=0) res[0][64]=a27;
  a29=(a29*a03);
  a57=(a57*a01);
  a29=(a29+a57);
  a57=arg[3]? arg[3][184] : 0;
  a29=(a29-a57);
  a29=(a29*a30);
  if (res[0]!=0) res[0][65]=a29;
  a31=(a31*a03);
  a58=(a58*a01);
  a31=(a31+a58);
  a58=arg[3]? arg[3][187] : 0;
  a31=(a31-a58);
  a31=(a31*a32);
  if (res[0]!=0) res[0][66]=a31;
  a33=(a33*a03);
  a59=(a59*a01);
  a33=(a33+a59);
  a59=arg[3]? arg[3][190] : 0;
  a33=(a33-a59);
  a33=(a33*a34);
  if (res[0]!=0) res[0][67]=a33;
  a35=(a35*a03);
  a60=(a60*a01);
  a35=(a35+a60);
  a60=arg[3]? arg[3][193] : 0;
  a35=(a35-a60);
  a35=(a35*a36);
  if (res[0]!=0) res[0][68]=a35;
  a37=(a37*a03);
  a61=(a61*a01);
  a37=(a37+a61);
  a61=arg[3]? arg[3][196] : 0;
  a37=(a37-a61);
  a37=(a37*a38);
  if (res[0]!=0) res[0][69]=a37;
  a39=(a39*a03);
  a62=(a62*a01);
  a39=(a39+a62);
  a62=arg[3]? arg[3][199] : 0;
  a39=(a39-a62);
  a39=(a39*a40);
  if (res[0]!=0) res[0][70]=a39;
  a41=(a41*a03);
  a63=(a63*a01);
  a41=(a41+a63);
  a63=arg[3]? arg[3][202] : 0;
  a41=(a41-a63);
  a41=(a41*a42);
  if (res[0]!=0) res[0][71]=a41;
  return 0;
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ddmr_constr_h_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ddmr_constr_h_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ddmr_constr_h_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void ddmr_constr_h_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ddmr_constr_h_fun_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ddmr_constr_h_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ddmr_constr_h_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ddmr_constr_h_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ddmr_constr_h_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ddmr_constr_h_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ddmr_constr_h_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 1*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
