/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ddmr_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {22, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {203, 1, 1};
static const casadi_int casadi_s4[3] = {72, 1, 1};
static const casadi_int casadi_s5[257] = 
  {29, 72, 0, 2, 4, 6, 8, 10,
  12, 14, 16, 18, 20, 22, 24, 26,
  28, 30, 32, 34, 36, 38, 40, 42,
  44, 46, 48, 50, 52, 54, 56, 58,
  60, 62, 64, 66, 68, 70, 72, 74,
  76, 78, 80, 82, 84, 86, 88, 90,
  92, 94, 96, 98, 100, 102, 122, 125,
  128, 131, 134, 137, 140, 143, 146, 149,
  152, 155, 158, 161, 164, 167, 170, 173,
  176, 179, 182, 25, 26, 25, 26, 27,
  28, 27, 28, 22, 23, 22, 23, 22,
  23, 22, 23, 22, 23, 22, 23, 22,
  23, 22, 23, 22, 23, 22, 23, 22,
  23, 22, 23, 22, 23, 22, 23, 22,
  23, 22, 23, 22, 23, 22, 23, 22,
  23, 22, 23, 22, 23, 22, 23, 22,
  23, 22, 23, 22, 23, 22, 23, 22,
  23, 22, 23, 22, 23, 22, 23, 22,
  23, 22, 23, 22, 23, 22, 23, 22,
  23, 22, 23, 22, 23, 22, 23, 22,
  23, 22, 23, 22, 23, 22, 23, 22,
  23, 22, 23, 22, 23, 22, 23, 22,
  23, 2, 3, 4, 5, 6, 7, 8,
  9, 10, 11, 12, 13, 14, 15, 16,
  17, 18, 19, 20, 21, 2, 22, 23,
  3, 22, 23, 4, 22, 23, 5, 22,
  23, 6, 22, 23, 7, 22, 23, 8,
  22, 23, 9, 22, 23, 10, 22, 23,
  11, 22, 23, 12, 22, 23, 13, 22,
  23, 14, 22, 23, 15, 22, 23, 16,
  22, 23, 17, 22, 23, 18, 22, 23,
  19, 22, 23, 20, 22, 23, 21, 22,
  23};
static const casadi_int casadi_s6[3] = {72, 0, 1};

/* ddmr_constr_h_fun_jac_uxt_zt:(i0[7],i1[22],i2[0],i3[203])->(o0[72],o1[29x72,182nz],o2[72x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108, a109, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119;
  casadi_real a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a130, a131;
  casadi_real a132, a133, a134, a135, a136, a137, a138, a139, a140, a141, a142, a143;
  casadi_real a144, a145, a146, a147, a148, a149, a150, a151, a152, a153, a154, a155;
  casadi_real a156, a157, a158, a159, a160, a161, a162, a163, a164, a165, a166, a167;
  casadi_real a168, a169, a170, a171, a172, a173, a174, a175, a176, a177, a178;
  a000=arg[0]? arg[0][3] : 0;
  a001=2.9999999999999999e-01;
  a002=arg[0]? arg[0][4] : 0;
  a002=(a001*a002);
  a003=(a000-a002);
  if (res[0]!=0) res[0][0]=a003;
  a000=(a000+a002);
  if (res[0]!=0) res[0][1]=a000;
  a000=arg[0]? arg[0][5] : 0;
  a002=arg[0]? arg[0][6] : 0;
  a002=(a001*a002);
  a003=(a000-a002);
  if (res[0]!=0) res[0][2]=a003;
  a000=(a000+a002);
  if (res[0]!=0) res[0][3]=a000;
  a000=arg[3]? arg[3][2] : 0;
  a002=arg[0]? arg[0][1] : 0;
  a003=arg[3]? arg[3][1] : 0;
  a003=(a002-a003);
  a003=(a000*a003);
  a004=arg[3]? arg[3][3] : 0;
  a005=arg[0]? arg[0][0] : 0;
  a006=arg[3]? arg[3][0] : 0;
  a006=(a005-a006);
  a006=(a004*a006);
  a003=(a003-a006);
  if (res[0]!=0) res[0][4]=a003;
  a003=arg[3]? arg[3][6] : 0;
  a006=arg[3]? arg[3][5] : 0;
  a006=(a002-a006);
  a006=(a003*a006);
  a007=arg[3]? arg[3][7] : 0;
  a008=arg[3]? arg[3][4] : 0;
  a008=(a005-a008);
  a008=(a007*a008);
  a006=(a006-a008);
  if (res[0]!=0) res[0][5]=a006;
  a006=arg[3]? arg[3][8] : 0;
  a006=(a005-a006);
  a008=casadi_sq(a006);
  a009=arg[3]? arg[3][9] : 0;
  a009=(a002-a009);
  a010=casadi_sq(a009);
  a008=(a008+a010);
  a010=arg[3]? arg[3][10] : 0;
  a008=(a008-a010);
  if (res[0]!=0) res[0][6]=a008;
  a008=arg[3]? arg[3][11] : 0;
  a008=(a005-a008);
  a010=casadi_sq(a008);
  a011=arg[3]? arg[3][12] : 0;
  a011=(a002-a011);
  a012=casadi_sq(a011);
  a010=(a010+a012);
  a012=arg[3]? arg[3][13] : 0;
  a010=(a010-a012);
  if (res[0]!=0) res[0][7]=a010;
  a010=arg[3]? arg[3][14] : 0;
  a010=(a005-a010);
  a012=casadi_sq(a010);
  a013=arg[3]? arg[3][15] : 0;
  a013=(a002-a013);
  a014=casadi_sq(a013);
  a012=(a012+a014);
  a014=arg[3]? arg[3][16] : 0;
  a012=(a012-a014);
  if (res[0]!=0) res[0][8]=a012;
  a012=arg[3]? arg[3][17] : 0;
  a012=(a005-a012);
  a014=casadi_sq(a012);
  a015=arg[3]? arg[3][18] : 0;
  a015=(a002-a015);
  a016=casadi_sq(a015);
  a014=(a014+a016);
  a016=arg[3]? arg[3][19] : 0;
  a014=(a014-a016);
  if (res[0]!=0) res[0][9]=a014;
  a014=arg[3]? arg[3][20] : 0;
  a014=(a005-a014);
  a016=casadi_sq(a014);
  a017=arg[3]? arg[3][21] : 0;
  a017=(a002-a017);
  a018=casadi_sq(a017);
  a016=(a016+a018);
  a018=arg[3]? arg[3][22] : 0;
  a016=(a016-a018);
  if (res[0]!=0) res[0][10]=a016;
  a016=arg[3]? arg[3][23] : 0;
  a016=(a005-a016);
  a018=casadi_sq(a016);
  a019=arg[3]? arg[3][24] : 0;
  a019=(a002-a019);
  a020=casadi_sq(a019);
  a018=(a018+a020);
  a020=arg[3]? arg[3][25] : 0;
  a018=(a018-a020);
  if (res[0]!=0) res[0][11]=a018;
  a018=arg[3]? arg[3][26] : 0;
  a018=(a005-a018);
  a020=casadi_sq(a018);
  a021=arg[3]? arg[3][27] : 0;
  a021=(a002-a021);
  a022=casadi_sq(a021);
  a020=(a020+a022);
  a022=arg[3]? arg[3][28] : 0;
  a020=(a020-a022);
  if (res[0]!=0) res[0][12]=a020;
  a020=arg[3]? arg[3][29] : 0;
  a020=(a005-a020);
  a022=casadi_sq(a020);
  a023=arg[3]? arg[3][30] : 0;
  a023=(a002-a023);
  a024=casadi_sq(a023);
  a022=(a022+a024);
  a024=arg[3]? arg[3][31] : 0;
  a022=(a022-a024);
  if (res[0]!=0) res[0][13]=a022;
  a022=arg[3]? arg[3][32] : 0;
  a022=(a005-a022);
  a024=casadi_sq(a022);
  a025=arg[3]? arg[3][33] : 0;
  a025=(a002-a025);
  a026=casadi_sq(a025);
  a024=(a024+a026);
  a026=arg[3]? arg[3][34] : 0;
  a024=(a024-a026);
  if (res[0]!=0) res[0][14]=a024;
  a024=arg[3]? arg[3][35] : 0;
  a024=(a005-a024);
  a026=casadi_sq(a024);
  a027=arg[3]? arg[3][36] : 0;
  a027=(a002-a027);
  a028=casadi_sq(a027);
  a026=(a026+a028);
  a028=arg[3]? arg[3][37] : 0;
  a026=(a026-a028);
  if (res[0]!=0) res[0][15]=a026;
  a026=arg[3]? arg[3][38] : 0;
  a026=(a005-a026);
  a028=casadi_sq(a026);
  a029=arg[3]? arg[3][39] : 0;
  a029=(a002-a029);
  a030=casadi_sq(a029);
  a028=(a028+a030);
  a030=arg[3]? arg[3][40] : 0;
  a028=(a028-a030);
  if (res[0]!=0) res[0][16]=a028;
  a028=arg[3]? arg[3][41] : 0;
  a028=(a005-a028);
  a030=casadi_sq(a028);
  a031=arg[3]? arg[3][42] : 0;
  a031=(a002-a031);
  a032=casadi_sq(a031);
  a030=(a030+a032);
  a032=arg[3]? arg[3][43] : 0;
  a030=(a030-a032);
  if (res[0]!=0) res[0][17]=a030;
  a030=arg[3]? arg[3][44] : 0;
  a030=(a005-a030);
  a032=casadi_sq(a030);
  a033=arg[3]? arg[3][45] : 0;
  a033=(a002-a033);
  a034=casadi_sq(a033);
  a032=(a032+a034);
  a034=arg[3]? arg[3][46] : 0;
  a032=(a032-a034);
  if (res[0]!=0) res[0][18]=a032;
  a032=arg[3]? arg[3][47] : 0;
  a032=(a005-a032);
  a034=casadi_sq(a032);
  a035=arg[3]? arg[3][48] : 0;
  a035=(a002-a035);
  a036=casadi_sq(a035);
  a034=(a034+a036);
  a036=arg[3]? arg[3][49] : 0;
  a034=(a034-a036);
  if (res[0]!=0) res[0][19]=a034;
  a034=arg[3]? arg[3][50] : 0;
  a034=(a005-a034);
  a036=casadi_sq(a034);
  a037=arg[3]? arg[3][51] : 0;
  a037=(a002-a037);
  a038=casadi_sq(a037);
  a036=(a036+a038);
  a038=arg[3]? arg[3][52] : 0;
  a036=(a036-a038);
  if (res[0]!=0) res[0][20]=a036;
  a036=arg[3]? arg[3][53] : 0;
  a036=(a005-a036);
  a038=casadi_sq(a036);
  a039=arg[3]? arg[3][54] : 0;
  a039=(a002-a039);
  a040=casadi_sq(a039);
  a038=(a038+a040);
  a040=arg[3]? arg[3][55] : 0;
  a038=(a038-a040);
  if (res[0]!=0) res[0][21]=a038;
  a038=arg[3]? arg[3][56] : 0;
  a038=(a005-a038);
  a040=casadi_sq(a038);
  a041=arg[3]? arg[3][57] : 0;
  a041=(a002-a041);
  a042=casadi_sq(a041);
  a040=(a040+a042);
  a042=arg[3]? arg[3][58] : 0;
  a040=(a040-a042);
  if (res[0]!=0) res[0][22]=a040;
  a040=arg[3]? arg[3][59] : 0;
  a040=(a005-a040);
  a042=casadi_sq(a040);
  a043=arg[3]? arg[3][60] : 0;
  a043=(a002-a043);
  a044=casadi_sq(a043);
  a042=(a042+a044);
  a044=arg[3]? arg[3][61] : 0;
  a042=(a042-a044);
  if (res[0]!=0) res[0][23]=a042;
  a042=arg[3]? arg[3][62] : 0;
  a042=(a005-a042);
  a044=casadi_sq(a042);
  a045=arg[3]? arg[3][63] : 0;
  a045=(a002-a045);
  a046=casadi_sq(a045);
  a044=(a044+a046);
  a046=arg[3]? arg[3][64] : 0;
  a044=(a044-a046);
  if (res[0]!=0) res[0][24]=a044;
  a044=arg[3]? arg[3][65] : 0;
  a044=(a005-a044);
  a046=casadi_sq(a044);
  a047=arg[3]? arg[3][66] : 0;
  a047=(a002-a047);
  a048=casadi_sq(a047);
  a046=(a046+a048);
  a048=arg[3]? arg[3][67] : 0;
  a046=(a046-a048);
  if (res[0]!=0) res[0][25]=a046;
  a046=arg[3]? arg[3][68] : 0;
  a046=(a005-a046);
  a048=casadi_sq(a046);
  a049=arg[3]? arg[3][69] : 0;
  a049=(a002-a049);
  a050=casadi_sq(a049);
  a048=(a048+a050);
  a050=arg[3]? arg[3][70] : 0;
  a048=(a048-a050);
  if (res[0]!=0) res[0][26]=a048;
  a048=arg[3]? arg[3][71] : 0;
  a048=(a005-a048);
  a050=casadi_sq(a048);
  a051=arg[3]? arg[3][72] : 0;
  a051=(a002-a051);
  a052=casadi_sq(a051);
  a050=(a050+a052);
  a052=arg[3]? arg[3][73] : 0;
  a050=(a050-a052);
  if (res[0]!=0) res[0][27]=a050;
  a050=arg[3]? arg[3][74] : 0;
  a050=(a005-a050);
  a052=casadi_sq(a050);
  a053=arg[3]? arg[3][75] : 0;
  a053=(a002-a053);
  a054=casadi_sq(a053);
  a052=(a052+a054);
  a054=arg[3]? arg[3][76] : 0;
  a052=(a052-a054);
  if (res[0]!=0) res[0][28]=a052;
  a052=arg[3]? arg[3][77] : 0;
  a052=(a005-a052);
  a054=casadi_sq(a052);
  a055=arg[3]? arg[3][78] : 0;
  a055=(a002-a055);
  a056=casadi_sq(a055);
  a054=(a054+a056);
  a056=arg[3]? arg[3][79] : 0;
  a054=(a054-a056);
  if (res[0]!=0) res[0][29]=a054;
  a054=arg[3]? arg[3][80] : 0;
  a054=(a005-a054);
  a056=casadi_sq(a054);
  a057=arg[3]? arg[3][81] : 0;
  a057=(a002-a057);
  a058=casadi_sq(a057);
  a056=(a056+a058);
  a058=arg[3]? arg[3][82] : 0;
  a056=(a056-a058);
  if (res[0]!=0) res[0][30]=a056;
  a056=arg[3]? arg[3][83] : 0;
  a056=(a005-a056);
  a058=casadi_sq(a056);
  a059=arg[3]? arg[3][84] : 0;
  a059=(a002-a059);
  a060=casadi_sq(a059);
  a058=(a058+a060);
  a060=arg[3]? arg[3][85] : 0;
  a058=(a058-a060);
  if (res[0]!=0) res[0][31]=a058;
  a058=arg[3]? arg[3][86] : 0;
  a058=(a005-a058);
  a060=casadi_sq(a058);
  a061=arg[3]? arg[3][87] : 0;
  a061=(a002-a061);
  a062=casadi_sq(a061);
  a060=(a060+a062);
  a062=arg[3]? arg[3][88] : 0;
  a060=(a060-a062);
  if (res[0]!=0) res[0][32]=a060;
  a060=arg[3]? arg[3][89] : 0;
  a060=(a005-a060);
  a062=casadi_sq(a060);
  a063=arg[3]? arg[3][90] : 0;
  a063=(a002-a063);
  a064=casadi_sq(a063);
  a062=(a062+a064);
  a064=arg[3]? arg[3][91] : 0;
  a062=(a062-a064);
  if (res[0]!=0) res[0][33]=a062;
  a062=arg[3]? arg[3][92] : 0;
  a062=(a005-a062);
  a064=casadi_sq(a062);
  a065=arg[3]? arg[3][93] : 0;
  a065=(a002-a065);
  a066=casadi_sq(a065);
  a064=(a064+a066);
  a066=arg[3]? arg[3][94] : 0;
  a064=(a064-a066);
  if (res[0]!=0) res[0][34]=a064;
  a064=arg[3]? arg[3][95] : 0;
  a064=(a005-a064);
  a066=casadi_sq(a064);
  a067=arg[3]? arg[3][96] : 0;
  a067=(a002-a067);
  a068=casadi_sq(a067);
  a066=(a066+a068);
  a068=arg[3]? arg[3][97] : 0;
  a066=(a066-a068);
  if (res[0]!=0) res[0][35]=a066;
  a066=arg[3]? arg[3][98] : 0;
  a066=(a005-a066);
  a068=casadi_sq(a066);
  a069=arg[3]? arg[3][99] : 0;
  a069=(a002-a069);
  a070=casadi_sq(a069);
  a068=(a068+a070);
  a070=arg[3]? arg[3][100] : 0;
  a068=(a068-a070);
  if (res[0]!=0) res[0][36]=a068;
  a068=arg[3]? arg[3][101] : 0;
  a068=(a005-a068);
  a070=casadi_sq(a068);
  a071=arg[3]? arg[3][102] : 0;
  a071=(a002-a071);
  a072=casadi_sq(a071);
  a070=(a070+a072);
  a072=arg[3]? arg[3][103] : 0;
  a070=(a070-a072);
  if (res[0]!=0) res[0][37]=a070;
  a070=arg[3]? arg[3][104] : 0;
  a070=(a005-a070);
  a072=casadi_sq(a070);
  a073=arg[3]? arg[3][105] : 0;
  a073=(a002-a073);
  a074=casadi_sq(a073);
  a072=(a072+a074);
  a074=arg[3]? arg[3][106] : 0;
  a072=(a072-a074);
  if (res[0]!=0) res[0][38]=a072;
  a072=arg[3]? arg[3][107] : 0;
  a072=(a005-a072);
  a074=casadi_sq(a072);
  a075=arg[3]? arg[3][108] : 0;
  a075=(a002-a075);
  a076=casadi_sq(a075);
  a074=(a074+a076);
  a076=arg[3]? arg[3][109] : 0;
  a074=(a074-a076);
  if (res[0]!=0) res[0][39]=a074;
  a074=arg[3]? arg[3][110] : 0;
  a074=(a005-a074);
  a076=casadi_sq(a074);
  a077=arg[3]? arg[3][111] : 0;
  a077=(a002-a077);
  a078=casadi_sq(a077);
  a076=(a076+a078);
  a078=arg[3]? arg[3][112] : 0;
  a076=(a076-a078);
  if (res[0]!=0) res[0][40]=a076;
  a076=arg[3]? arg[3][113] : 0;
  a076=(a005-a076);
  a078=casadi_sq(a076);
  a079=arg[3]? arg[3][114] : 0;
  a079=(a002-a079);
  a080=casadi_sq(a079);
  a078=(a078+a080);
  a080=arg[3]? arg[3][115] : 0;
  a078=(a078-a080);
  if (res[0]!=0) res[0][41]=a078;
  a078=arg[3]? arg[3][116] : 0;
  a078=(a005-a078);
  a080=casadi_sq(a078);
  a081=arg[3]? arg[3][117] : 0;
  a081=(a002-a081);
  a082=casadi_sq(a081);
  a080=(a080+a082);
  a082=arg[3]? arg[3][118] : 0;
  a080=(a080-a082);
  if (res[0]!=0) res[0][42]=a080;
  a080=arg[3]? arg[3][119] : 0;
  a080=(a005-a080);
  a082=casadi_sq(a080);
  a083=arg[3]? arg[3][120] : 0;
  a083=(a002-a083);
  a084=casadi_sq(a083);
  a082=(a082+a084);
  a084=arg[3]? arg[3][121] : 0;
  a082=(a082-a084);
  if (res[0]!=0) res[0][43]=a082;
  a082=arg[3]? arg[3][122] : 0;
  a082=(a005-a082);
  a084=casadi_sq(a082);
  a085=arg[3]? arg[3][123] : 0;
  a085=(a002-a085);
  a086=casadi_sq(a085);
  a084=(a084+a086);
  a086=arg[3]? arg[3][124] : 0;
  a084=(a084-a086);
  if (res[0]!=0) res[0][44]=a084;
  a084=arg[3]? arg[3][125] : 0;
  a084=(a005-a084);
  a086=casadi_sq(a084);
  a087=arg[3]? arg[3][126] : 0;
  a087=(a002-a087);
  a088=casadi_sq(a087);
  a086=(a086+a088);
  a088=arg[3]? arg[3][127] : 0;
  a086=(a086-a088);
  if (res[0]!=0) res[0][45]=a086;
  a086=arg[3]? arg[3][128] : 0;
  a086=(a005-a086);
  a088=casadi_sq(a086);
  a089=arg[3]? arg[3][129] : 0;
  a089=(a002-a089);
  a090=casadi_sq(a089);
  a088=(a088+a090);
  a090=arg[3]? arg[3][130] : 0;
  a088=(a088-a090);
  if (res[0]!=0) res[0][46]=a088;
  a088=arg[3]? arg[3][131] : 0;
  a088=(a005-a088);
  a090=casadi_sq(a088);
  a091=arg[3]? arg[3][132] : 0;
  a091=(a002-a091);
  a092=casadi_sq(a091);
  a090=(a090+a092);
  a092=arg[3]? arg[3][133] : 0;
  a090=(a090-a092);
  if (res[0]!=0) res[0][47]=a090;
  a090=arg[3]? arg[3][134] : 0;
  a090=(a005-a090);
  a092=casadi_sq(a090);
  a093=arg[3]? arg[3][135] : 0;
  a093=(a002-a093);
  a094=casadi_sq(a093);
  a092=(a092+a094);
  a094=arg[3]? arg[3][136] : 0;
  a092=(a092-a094);
  if (res[0]!=0) res[0][48]=a092;
  a092=arg[3]? arg[3][137] : 0;
  a092=(a005-a092);
  a094=casadi_sq(a092);
  a095=arg[3]? arg[3][138] : 0;
  a095=(a002-a095);
  a096=casadi_sq(a095);
  a094=(a094+a096);
  a096=arg[3]? arg[3][139] : 0;
  a094=(a094-a096);
  if (res[0]!=0) res[0][49]=a094;
  a094=arg[3]? arg[3][140] : 0;
  a094=(a005-a094);
  a096=casadi_sq(a094);
  a097=arg[3]? arg[3][141] : 0;
  a097=(a002-a097);
  a098=casadi_sq(a097);
  a096=(a096+a098);
  a098=arg[3]? arg[3][142] : 0;
  a096=(a096-a098);
  if (res[0]!=0) res[0][50]=a096;
  a096=arg[3]? arg[3][143] : 0;
  a098=arg[1]? arg[1][2] : 0;
  a099=(a096*a098);
  a100=arg[3]? arg[3][146] : 0;
  a101=arg[1]? arg[1][3] : 0;
  a102=(a100*a101);
  a099=(a099+a102);
  a102=arg[3]? arg[3][149] : 0;
  a103=arg[1]? arg[1][4] : 0;
  a104=(a102*a103);
  a099=(a099+a104);
  a104=arg[3]? arg[3][152] : 0;
  a105=arg[1]? arg[1][5] : 0;
  a106=(a104*a105);
  a099=(a099+a106);
  a106=arg[3]? arg[3][155] : 0;
  a107=arg[1]? arg[1][6] : 0;
  a108=(a106*a107);
  a099=(a099+a108);
  a108=arg[3]? arg[3][158] : 0;
  a109=arg[1]? arg[1][7] : 0;
  a110=(a108*a109);
  a099=(a099+a110);
  a110=arg[3]? arg[3][161] : 0;
  a111=arg[1]? arg[1][8] : 0;
  a112=(a110*a111);
  a099=(a099+a112);
  a112=arg[3]? arg[3][164] : 0;
  a113=arg[1]? arg[1][9] : 0;
  a114=(a112*a113);
  a099=(a099+a114);
  a114=arg[3]? arg[3][167] : 0;
  a115=arg[1]? arg[1][10] : 0;
  a116=(a114*a115);
  a099=(a099+a116);
  a116=arg[3]? arg[3][170] : 0;
  a117=arg[1]? arg[1][11] : 0;
  a118=(a116*a117);
  a099=(a099+a118);
  a118=arg[3]? arg[3][173] : 0;
  a119=arg[1]? arg[1][12] : 0;
  a120=(a118*a119);
  a099=(a099+a120);
  a120=arg[3]? arg[3][176] : 0;
  a121=arg[1]? arg[1][13] : 0;
  a122=(a120*a121);
  a099=(a099+a122);
  a122=arg[3]? arg[3][179] : 0;
  a123=arg[1]? arg[1][14] : 0;
  a124=(a122*a123);
  a099=(a099+a124);
  a124=arg[3]? arg[3][182] : 0;
  a125=arg[1]? arg[1][15] : 0;
  a126=(a124*a125);
  a099=(a099+a126);
  a126=arg[3]? arg[3][185] : 0;
  a127=arg[1]? arg[1][16] : 0;
  a128=(a126*a127);
  a099=(a099+a128);
  a128=arg[3]? arg[3][188] : 0;
  a129=arg[1]? arg[1][17] : 0;
  a130=(a128*a129);
  a099=(a099+a130);
  a130=arg[3]? arg[3][191] : 0;
  a131=arg[1]? arg[1][18] : 0;
  a132=(a130*a131);
  a099=(a099+a132);
  a132=arg[3]? arg[3][194] : 0;
  a133=arg[1]? arg[1][19] : 0;
  a134=(a132*a133);
  a099=(a099+a134);
  a134=arg[3]? arg[3][197] : 0;
  a135=arg[1]? arg[1][20] : 0;
  a136=(a134*a135);
  a099=(a099+a136);
  a136=arg[3]? arg[3][200] : 0;
  a137=arg[1]? arg[1][21] : 0;
  a138=(a136*a137);
  a099=(a099+a138);
  a138=casadi_sq(a099);
  a139=arg[3]? arg[3][144] : 0;
  a140=(a139*a098);
  a141=arg[3]? arg[3][147] : 0;
  a142=(a141*a101);
  a140=(a140+a142);
  a142=arg[3]? arg[3][150] : 0;
  a143=(a142*a103);
  a140=(a140+a143);
  a143=arg[3]? arg[3][153] : 0;
  a144=(a143*a105);
  a140=(a140+a144);
  a144=arg[3]? arg[3][156] : 0;
  a145=(a144*a107);
  a140=(a140+a145);
  a145=arg[3]? arg[3][159] : 0;
  a146=(a145*a109);
  a140=(a140+a146);
  a146=arg[3]? arg[3][162] : 0;
  a147=(a146*a111);
  a140=(a140+a147);
  a147=arg[3]? arg[3][165] : 0;
  a148=(a147*a113);
  a140=(a140+a148);
  a148=arg[3]? arg[3][168] : 0;
  a149=(a148*a115);
  a140=(a140+a149);
  a149=arg[3]? arg[3][171] : 0;
  a150=(a149*a117);
  a140=(a140+a150);
  a150=arg[3]? arg[3][174] : 0;
  a151=(a150*a119);
  a140=(a140+a151);
  a151=arg[3]? arg[3][177] : 0;
  a152=(a151*a121);
  a140=(a140+a152);
  a152=arg[3]? arg[3][180] : 0;
  a153=(a152*a123);
  a140=(a140+a153);
  a153=arg[3]? arg[3][183] : 0;
  a154=(a153*a125);
  a140=(a140+a154);
  a154=arg[3]? arg[3][186] : 0;
  a155=(a154*a127);
  a140=(a140+a155);
  a155=arg[3]? arg[3][189] : 0;
  a156=(a155*a129);
  a140=(a140+a156);
  a156=arg[3]? arg[3][192] : 0;
  a157=(a156*a131);
  a140=(a140+a157);
  a157=arg[3]? arg[3][195] : 0;
  a158=(a157*a133);
  a140=(a140+a158);
  a158=arg[3]? arg[3][198] : 0;
  a159=(a158*a135);
  a140=(a140+a159);
  a159=arg[3]? arg[3][201] : 0;
  a160=(a159*a137);
  a140=(a140+a160);
  a160=casadi_sq(a140);
  a138=(a138+a160);
  if (res[0]!=0) res[0][51]=a138;
  a138=(a096*a005);
  a160=(a139*a002);
  a138=(a138+a160);
  a160=arg[3]? arg[3][145] : 0;
  a138=(a138-a160);
  a160=(a138*a098);
  if (res[0]!=0) res[0][52]=a160;
  a160=(a100*a005);
  a161=(a141*a002);
  a160=(a160+a161);
  a161=arg[3]? arg[3][148] : 0;
  a160=(a160-a161);
  a161=(a160*a101);
  if (res[0]!=0) res[0][53]=a161;
  a161=(a102*a005);
  a162=(a142*a002);
  a161=(a161+a162);
  a162=arg[3]? arg[3][151] : 0;
  a161=(a161-a162);
  a162=(a161*a103);
  if (res[0]!=0) res[0][54]=a162;
  a162=(a104*a005);
  a163=(a143*a002);
  a162=(a162+a163);
  a163=arg[3]? arg[3][154] : 0;
  a162=(a162-a163);
  a163=(a162*a105);
  if (res[0]!=0) res[0][55]=a163;
  a163=(a106*a005);
  a164=(a144*a002);
  a163=(a163+a164);
  a164=arg[3]? arg[3][157] : 0;
  a163=(a163-a164);
  a164=(a163*a107);
  if (res[0]!=0) res[0][56]=a164;
  a164=(a108*a005);
  a165=(a145*a002);
  a164=(a164+a165);
  a165=arg[3]? arg[3][160] : 0;
  a164=(a164-a165);
  a165=(a164*a109);
  if (res[0]!=0) res[0][57]=a165;
  a165=(a110*a005);
  a166=(a146*a002);
  a165=(a165+a166);
  a166=arg[3]? arg[3][163] : 0;
  a165=(a165-a166);
  a166=(a165*a111);
  if (res[0]!=0) res[0][58]=a166;
  a166=(a112*a005);
  a167=(a147*a002);
  a166=(a166+a167);
  a167=arg[3]? arg[3][166] : 0;
  a166=(a166-a167);
  a167=(a166*a113);
  if (res[0]!=0) res[0][59]=a167;
  a167=(a114*a005);
  a168=(a148*a002);
  a167=(a167+a168);
  a168=arg[3]? arg[3][169] : 0;
  a167=(a167-a168);
  a168=(a167*a115);
  if (res[0]!=0) res[0][60]=a168;
  a168=(a116*a005);
  a169=(a149*a002);
  a168=(a168+a169);
  a169=arg[3]? arg[3][172] : 0;
  a168=(a168-a169);
  a169=(a168*a117);
  if (res[0]!=0) res[0][61]=a169;
  a169=(a118*a005);
  a170=(a150*a002);
  a169=(a169+a170);
  a170=arg[3]? arg[3][175] : 0;
  a169=(a169-a170);
  a170=(a169*a119);
  if (res[0]!=0) res[0][62]=a170;
  a170=(a120*a005);
  a171=(a151*a002);
  a170=(a170+a171);
  a171=arg[3]? arg[3][178] : 0;
  a170=(a170-a171);
  a171=(a170*a121);
  if (res[0]!=0) res[0][63]=a171;
  a171=(a122*a005);
  a172=(a152*a002);
  a171=(a171+a172);
  a172=arg[3]? arg[3][181] : 0;
  a171=(a171-a172);
  a172=(a171*a123);
  if (res[0]!=0) res[0][64]=a172;
  a172=(a124*a005);
  a173=(a153*a002);
  a172=(a172+a173);
  a173=arg[3]? arg[3][184] : 0;
  a172=(a172-a173);
  a173=(a172*a125);
  if (res[0]!=0) res[0][65]=a173;
  a173=(a126*a005);
  a174=(a154*a002);
  a173=(a173+a174);
  a174=arg[3]? arg[3][187] : 0;
  a173=(a173-a174);
  a174=(a173*a127);
  if (res[0]!=0) res[0][66]=a174;
  a174=(a128*a005);
  a175=(a155*a002);
  a174=(a174+a175);
  a175=arg[3]? arg[3][190] : 0;
  a174=(a174-a175);
  a175=(a174*a129);
  if (res[0]!=0) res[0][67]=a175;
  a175=(a130*a005);
  a176=(a156*a002);
  a175=(a175+a176);
  a176=arg[3]? arg[3][193] : 0;
  a175=(a175-a176);
  a176=(a175*a131);
  if (res[0]!=0) res[0][68]=a176;
  a176=(a132*a005);
  a177=(a157*a002);
  a176=(a176+a177);
  a177=arg[3]? arg[3][196] : 0;
  a176=(a176-a177);
  a177=(a176*a133);
  if (res[0]!=0) res[0][69]=a177;
  a177=(a134*a005);
  a178=(a158*a002);
  a177=(a177+a178);
  a178=arg[3]? arg[3][199] : 0;
  a177=(a177-a178);
  a178=(a177*a135);
  if (res[0]!=0) res[0][70]=a178;
  a005=(a136*a005);
  a002=(a159*a002);
  a005=(a005+a002);
  a002=arg[3]? arg[3][202] : 0;
  a005=(a005-a002);
  a002=(a005*a137);
  if (res[0]!=0) res[0][71]=a002;
  a002=1.;
  if (res[1]!=0) res[1][0]=a002;
  a178=-2.9999999999999999e-01;
  if (res[1]!=0) res[1][1]=a178;
  if (res[1]!=0) res[1][2]=a002;
  if (res[1]!=0) res[1][3]=a001;
  if (res[1]!=0) res[1][4]=a002;
  if (res[1]!=0) res[1][5]=a178;
  if (res[1]!=0) res[1][6]=a002;
  if (res[1]!=0) res[1][7]=a001;
  a004=(-a004);
  if (res[1]!=0) res[1][8]=a004;
  if (res[1]!=0) res[1][9]=a000;
  a007=(-a007);
  if (res[1]!=0) res[1][10]=a007;
  if (res[1]!=0) res[1][11]=a003;
  a006=(a006+a006);
  if (res[1]!=0) res[1][12]=a006;
  a009=(a009+a009);
  if (res[1]!=0) res[1][13]=a009;
  a008=(a008+a008);
  if (res[1]!=0) res[1][14]=a008;
  a011=(a011+a011);
  if (res[1]!=0) res[1][15]=a011;
  a010=(a010+a010);
  if (res[1]!=0) res[1][16]=a010;
  a013=(a013+a013);
  if (res[1]!=0) res[1][17]=a013;
  a012=(a012+a012);
  if (res[1]!=0) res[1][18]=a012;
  a015=(a015+a015);
  if (res[1]!=0) res[1][19]=a015;
  a014=(a014+a014);
  if (res[1]!=0) res[1][20]=a014;
  a017=(a017+a017);
  if (res[1]!=0) res[1][21]=a017;
  a016=(a016+a016);
  if (res[1]!=0) res[1][22]=a016;
  a019=(a019+a019);
  if (res[1]!=0) res[1][23]=a019;
  a018=(a018+a018);
  if (res[1]!=0) res[1][24]=a018;
  a021=(a021+a021);
  if (res[1]!=0) res[1][25]=a021;
  a020=(a020+a020);
  if (res[1]!=0) res[1][26]=a020;
  a023=(a023+a023);
  if (res[1]!=0) res[1][27]=a023;
  a022=(a022+a022);
  if (res[1]!=0) res[1][28]=a022;
  a025=(a025+a025);
  if (res[1]!=0) res[1][29]=a025;
  a024=(a024+a024);
  if (res[1]!=0) res[1][30]=a024;
  a027=(a027+a027);
  if (res[1]!=0) res[1][31]=a027;
  a026=(a026+a026);
  if (res[1]!=0) res[1][32]=a026;
  a029=(a029+a029);
  if (res[1]!=0) res[1][33]=a029;
  a028=(a028+a028);
  if (res[1]!=0) res[1][34]=a028;
  a031=(a031+a031);
  if (res[1]!=0) res[1][35]=a031;
  a030=(a030+a030);
  if (res[1]!=0) res[1][36]=a030;
  a033=(a033+a033);
  if (res[1]!=0) res[1][37]=a033;
  a032=(a032+a032);
  if (res[1]!=0) res[1][38]=a032;
  a035=(a035+a035);
  if (res[1]!=0) res[1][39]=a035;
  a034=(a034+a034);
  if (res[1]!=0) res[1][40]=a034;
  a037=(a037+a037);
  if (res[1]!=0) res[1][41]=a037;
  a036=(a036+a036);
  if (res[1]!=0) res[1][42]=a036;
  a039=(a039+a039);
  if (res[1]!=0) res[1][43]=a039;
  a038=(a038+a038);
  if (res[1]!=0) res[1][44]=a038;
  a041=(a041+a041);
  if (res[1]!=0) res[1][45]=a041;
  a040=(a040+a040);
  if (res[1]!=0) res[1][46]=a040;
  a043=(a043+a043);
  if (res[1]!=0) res[1][47]=a043;
  a042=(a042+a042);
  if (res[1]!=0) res[1][48]=a042;
  a045=(a045+a045);
  if (res[1]!=0) res[1][49]=a045;
  a044=(a044+a044);
  if (res[1]!=0) res[1][50]=a044;
  a047=(a047+a047);
  if (res[1]!=0) res[1][51]=a047;
  a046=(a046+a046);
  if (res[1]!=0) res[1][52]=a046;
  a049=(a049+a049);
  if (res[1]!=0) res[1][53]=a049;
  a048=(a048+a048);
  if (res[1]!=0) res[1][54]=a048;
  a051=(a051+a051);
  if (res[1]!=0) res[1][55]=a051;
  a050=(a050+a050);
  if (res[1]!=0) res[1][56]=a050;
  a053=(a053+a053);
  if (res[1]!=0) res[1][57]=a053;
  a052=(a052+a052);
  if (res[1]!=0) res[1][58]=a052;
  a055=(a055+a055);
  if (res[1]!=0) res[1][59]=a055;
  a054=(a054+a054);
  if (res[1]!=0) res[1][60]=a054;
  a057=(a057+a057);
  if (res[1]!=0) res[1][61]=a057;
  a056=(a056+a056);
  if (res[1]!=0) res[1][62]=a056;
  a059=(a059+a059);
  if (res[1]!=0) res[1][63]=a059;
  a058=(a058+a058);
  if (res[1]!=0) res[1][64]=a058;
  a061=(a061+a061);
  if (res[1]!=0) res[1][65]=a061;
  a060=(a060+a060);
  if (res[1]!=0) res[1][66]=a060;
  a063=(a063+a063);
  if (res[1]!=0) res[1][67]=a063;
  a062=(a062+a062);
  if (res[1]!=0) res[1][68]=a062;
  a065=(a065+a065);
  if (res[1]!=0) res[1][69]=a065;
  a064=(a064+a064);
  if (res[1]!=0) res[1][70]=a064;
  a067=(a067+a067);
  if (res[1]!=0) res[1][71]=a067;
  a066=(a066+a066);
  if (res[1]!=0) res[1][72]=a066;
  a069=(a069+a069);
  if (res[1]!=0) res[1][73]=a069;
  a068=(a068+a068);
  if (res[1]!=0) res[1][74]=a068;
  a071=(a071+a071);
  if (res[1]!=0) res[1][75]=a071;
  a070=(a070+a070);
  if (res[1]!=0) res[1][76]=a070;
  a073=(a073+a073);
  if (res[1]!=0) res[1][77]=a073;
  a072=(a072+a072);
  if (res[1]!=0) res[1][78]=a072;
  a075=(a075+a075);
  if (res[1]!=0) res[1][79]=a075;
  a074=(a074+a074);
  if (res[1]!=0) res[1][80]=a074;
  a077=(a077+a077);
  if (res[1]!=0) res[1][81]=a077;
  a076=(a076+a076);
  if (res[1]!=0) res[1][82]=a076;
  a079=(a079+a079);
  if (res[1]!=0) res[1][83]=a079;
  a078=(a078+a078);
  if (res[1]!=0) res[1][84]=a078;
  a081=(a081+a081);
  if (res[1]!=0) res[1][85]=a081;
  a080=(a080+a080);
  if (res[1]!=0) res[1][86]=a080;
  a083=(a083+a083);
  if (res[1]!=0) res[1][87]=a083;
  a082=(a082+a082);
  if (res[1]!=0) res[1][88]=a082;
  a085=(a085+a085);
  if (res[1]!=0) res[1][89]=a085;
  a084=(a084+a084);
  if (res[1]!=0) res[1][90]=a084;
  a087=(a087+a087);
  if (res[1]!=0) res[1][91]=a087;
  a086=(a086+a086);
  if (res[1]!=0) res[1][92]=a086;
  a089=(a089+a089);
  if (res[1]!=0) res[1][93]=a089;
  a088=(a088+a088);
  if (res[1]!=0) res[1][94]=a088;
  a091=(a091+a091);
  if (res[1]!=0) res[1][95]=a091;
  a090=(a090+a090);
  if (res[1]!=0) res[1][96]=a090;
  a093=(a093+a093);
  if (res[1]!=0) res[1][97]=a093;
  a092=(a092+a092);
  if (res[1]!=0) res[1][98]=a092;
  a095=(a095+a095);
  if (res[1]!=0) res[1][99]=a095;
  a094=(a094+a094);
  if (res[1]!=0) res[1][100]=a094;
  a097=(a097+a097);
  if (res[1]!=0) res[1][101]=a097;
  a099=(a099+a099);
  a097=(a099*a096);
  a140=(a140+a140);
  a094=(a140*a139);
  a097=(a097+a094);
  if (res[1]!=0) res[1][102]=a097;
  a097=(a099*a100);
  a094=(a140*a141);
  a097=(a097+a094);
  if (res[1]!=0) res[1][103]=a097;
  a097=(a099*a102);
  a094=(a140*a142);
  a097=(a097+a094);
  if (res[1]!=0) res[1][104]=a097;
  a097=(a099*a104);
  a094=(a140*a143);
  a097=(a097+a094);
  if (res[1]!=0) res[1][105]=a097;
  a097=(a099*a106);
  a094=(a140*a144);
  a097=(a097+a094);
  if (res[1]!=0) res[1][106]=a097;
  a097=(a099*a108);
  a094=(a140*a145);
  a097=(a097+a094);
  if (res[1]!=0) res[1][107]=a097;
  a097=(a099*a110);
  a094=(a140*a146);
  a097=(a097+a094);
  if (res[1]!=0) res[1][108]=a097;
  a097=(a099*a112);
  a094=(a140*a147);
  a097=(a097+a094);
  if (res[1]!=0) res[1][109]=a097;
  a097=(a099*a114);
  a094=(a140*a148);
  a097=(a097+a094);
  if (res[1]!=0) res[1][110]=a097;
  a097=(a099*a116);
  a094=(a140*a149);
  a097=(a097+a094);
  if (res[1]!=0) res[1][111]=a097;
  a097=(a099*a118);
  a094=(a140*a150);
  a097=(a097+a094);
  if (res[1]!=0) res[1][112]=a097;
  a097=(a099*a120);
  a094=(a140*a151);
  a097=(a097+a094);
  if (res[1]!=0) res[1][113]=a097;
  a097=(a099*a122);
  a094=(a140*a152);
  a097=(a097+a094);
  if (res[1]!=0) res[1][114]=a097;
  a097=(a099*a124);
  a094=(a140*a153);
  a097=(a097+a094);
  if (res[1]!=0) res[1][115]=a097;
  a097=(a099*a126);
  a094=(a140*a154);
  a097=(a097+a094);
  if (res[1]!=0) res[1][116]=a097;
  a097=(a099*a128);
  a094=(a140*a155);
  a097=(a097+a094);
  if (res[1]!=0) res[1][117]=a097;
  a097=(a099*a130);
  a094=(a140*a156);
  a097=(a097+a094);
  if (res[1]!=0) res[1][118]=a097;
  a097=(a099*a132);
  a094=(a140*a157);
  a097=(a097+a094);
  if (res[1]!=0) res[1][119]=a097;
  a097=(a099*a134);
  a094=(a140*a158);
  a097=(a097+a094);
  if (res[1]!=0) res[1][120]=a097;
  a099=(a099*a136);
  a140=(a140*a159);
  a099=(a099+a140);
  if (res[1]!=0) res[1][121]=a099;
  if (res[1]!=0) res[1][122]=a138;
  a096=(a098*a096);
  if (res[1]!=0) res[1][123]=a096;
  a098=(a098*a139);
  if (res[1]!=0) res[1][124]=a098;
  if (res[1]!=0) res[1][125]=a160;
  a100=(a101*a100);
  if (res[1]!=0) res[1][126]=a100;
  a101=(a101*a141);
  if (res[1]!=0) res[1][127]=a101;
  if (res[1]!=0) res[1][128]=a161;
  a102=(a103*a102);
  if (res[1]!=0) res[1][129]=a102;
  a103=(a103*a142);
  if (res[1]!=0) res[1][130]=a103;
  if (res[1]!=0) res[1][131]=a162;
  a104=(a105*a104);
  if (res[1]!=0) res[1][132]=a104;
  a105=(a105*a143);
  if (res[1]!=0) res[1][133]=a105;
  if (res[1]!=0) res[1][134]=a163;
  a106=(a107*a106);
  if (res[1]!=0) res[1][135]=a106;
  a107=(a107*a144);
  if (res[1]!=0) res[1][136]=a107;
  if (res[1]!=0) res[1][137]=a164;
  a108=(a109*a108);
  if (res[1]!=0) res[1][138]=a108;
  a109=(a109*a145);
  if (res[1]!=0) res[1][139]=a109;
  if (res[1]!=0) res[1][140]=a165;
  a110=(a111*a110);
  if (res[1]!=0) res[1][141]=a110;
  a111=(a111*a146);
  if (res[1]!=0) res[1][142]=a111;
  if (res[1]!=0) res[1][143]=a166;
  a112=(a113*a112);
  if (res[1]!=0) res[1][144]=a112;
  a113=(a113*a147);
  if (res[1]!=0) res[1][145]=a113;
  if (res[1]!=0) res[1][146]=a167;
  a114=(a115*a114);
  if (res[1]!=0) res[1][147]=a114;
  a115=(a115*a148);
  if (res[1]!=0) res[1][148]=a115;
  if (res[1]!=0) res[1][149]=a168;
  a116=(a117*a116);
  if (res[1]!=0) res[1][150]=a116;
  a117=(a117*a149);
  if (res[1]!=0) res[1][151]=a117;
  if (res[1]!=0) res[1][152]=a169;
  a118=(a119*a118);
  if (res[1]!=0) res[1][153]=a118;
  a119=(a119*a150);
  if (res[1]!=0) res[1][154]=a119;
  if (res[1]!=0) res[1][155]=a170;
  a120=(a121*a120);
  if (res[1]!=0) res[1][156]=a120;
  a121=(a121*a151);
  if (res[1]!=0) res[1][157]=a121;
  if (res[1]!=0) res[1][158]=a171;
  a122=(a123*a122);
  if (res[1]!=0) res[1][159]=a122;
  a123=(a123*a152);
  if (res[1]!=0) res[1][160]=a123;
  if (res[1]!=0) res[1][161]=a172;
  a124=(a125*a124);
  if (res[1]!=0) res[1][162]=a124;
  a125=(a125*a153);
  if (res[1]!=0) res[1][163]=a125;
  if (res[1]!=0) res[1][164]=a173;
  a126=(a127*a126);
  if (res[1]!=0) res[1][165]=a126;
  a127=(a127*a154);
  if (res[1]!=0) res[1][166]=a127;
  if (res[1]!=0) res[1][167]=a174;
  a128=(a129*a128);
  if (res[1]!=0) res[1][168]=a128;
  a129=(a129*a155);
  if (res[1]!=0) res[1][169]=a129;
  if (res[1]!=0) res[1][170]=a175;
  a130=(a131*a130);
  if (res[1]!=0) res[1][171]=a130;
  a131=(a131*a156);
  if (res[1]!=0) res[1][172]=a131;
  if (res[1]!=0) res[1][173]=a176;
  a132=(a133*a132);
  if (res[1]!=0) res[1][174]=a132;
  a133=(a133*a157);
  if (res[1]!=0) res[1][175]=a133;
  if (res[1]!=0) res[1][176]=a177;
  a134=(a135*a134);
  if (res[1]!=0) res[1][177]=a134;
  a135=(a135*a158);
  if (res[1]!=0) res[1][178]=a135;
  if (res[1]!=0) res[1][179]=a005;
  a136=(a137*a136);
  if (res[1]!=0) res[1][180]=a136;
  a137=(a137*a159);
  if (res[1]!=0) res[1][181]=a137;
  return 0;
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ddmr_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ddmr_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ddmr_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void ddmr_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ddmr_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ddmr_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real ddmr_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ddmr_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ddmr_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ddmr_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ddmr_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
