/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ddmr_constr_h_fun_jac_uxt_zt_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {22, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {98, 1, 1};
static const casadi_int casadi_s4[3] = {37, 1, 1};
static const casadi_int casadi_s5[152] = 
  {29, 37, 0, 2, 4, 6, 8, 10,
  12, 14, 16, 18, 20, 22, 24, 26,
  28, 30, 32, 52, 55, 58, 61, 64,
  67, 70, 73, 76, 79, 82, 85, 88,
  91, 94, 97, 100, 103, 106, 109, 112,
  25, 26, 25, 26, 27, 28, 27, 28,
  22, 23, 22, 23, 22, 23, 22, 23,
  22, 23, 22, 23, 22, 23, 22, 23,
  22, 23, 22, 23, 22, 23, 22, 23,
  2, 3, 4, 5, 6, 7, 8, 9,
  10, 11, 12, 13, 14, 15, 16, 17,
  18, 19, 20, 21, 2, 22, 23, 3,
  22, 23, 4, 22, 23, 5, 22, 23,
  6, 22, 23, 7, 22, 23, 8, 22,
  23, 9, 22, 23, 10, 22, 23, 11,
  22, 23, 12, 22, 23, 13, 22, 23,
  14, 22, 23, 15, 22, 23, 16, 22,
  23, 17, 22, 23, 18, 22, 23, 19,
  22, 23, 20, 22, 23, 21, 22, 23};
static const casadi_int casadi_s6[3] = {37, 0, 1};

/* ddmr_constr_h_fun_jac_uxt_zt:(i0[7],i1[22],i2[0],i3[98])->(o0[37],o1[29x37,112nz],o2[37x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a000, a001, a002, a003, a004, a005, a006, a007, a008, a009, a010, a011;
  casadi_real a012, a013, a014, a015, a016, a017, a018, a019, a020, a021, a022, a023;
  casadi_real a024, a025, a026, a027, a028, a029, a030, a031, a032, a033, a034, a035;
  casadi_real a036, a037, a038, a039, a040, a041, a042, a043, a044, a045, a046, a047;
  casadi_real a048, a049, a050, a051, a052, a053, a054, a055, a056, a057, a058, a059;
  casadi_real a060, a061, a062, a063, a064, a065, a066, a067, a068, a069, a070, a071;
  casadi_real a072, a073, a074, a075, a076, a077, a078, a079, a080, a081, a082, a083;
  casadi_real a084, a085, a086, a087, a088, a089, a090, a091, a092, a093, a094, a095;
  casadi_real a096, a097, a098, a099, a100, a101, a102, a103, a104, a105, a106, a107;
  casadi_real a108;
  a000=arg[0]? arg[0][3] : 0;
  a001=2.9999999999999999e-01;
  a002=arg[0]? arg[0][4] : 0;
  a002=(a001*a002);
  a003=(a000-a002);
  if (res[0]!=0) res[0][0]=a003;
  a000=(a000+a002);
  if (res[0]!=0) res[0][1]=a000;
  a000=arg[0]? arg[0][5] : 0;
  a002=arg[0]? arg[0][6] : 0;
  a002=(a001*a002);
  a003=(a000-a002);
  if (res[0]!=0) res[0][2]=a003;
  a000=(a000+a002);
  if (res[0]!=0) res[0][3]=a000;
  a000=arg[3]? arg[3][2] : 0;
  a002=arg[0]? arg[0][1] : 0;
  a003=arg[3]? arg[3][1] : 0;
  a003=(a002-a003);
  a003=(a000*a003);
  a004=arg[3]? arg[3][3] : 0;
  a005=arg[0]? arg[0][0] : 0;
  a006=arg[3]? arg[3][0] : 0;
  a006=(a005-a006);
  a006=(a004*a006);
  a003=(a003-a006);
  if (res[0]!=0) res[0][4]=a003;
  a003=arg[3]? arg[3][6] : 0;
  a006=arg[3]? arg[3][5] : 0;
  a006=(a002-a006);
  a006=(a003*a006);
  a007=arg[3]? arg[3][7] : 0;
  a008=arg[3]? arg[3][4] : 0;
  a008=(a005-a008);
  a008=(a007*a008);
  a006=(a006-a008);
  if (res[0]!=0) res[0][5]=a006;
  a006=arg[3]? arg[3][8] : 0;
  a006=(a005-a006);
  a008=casadi_sq(a006);
  a009=arg[3]? arg[3][9] : 0;
  a009=(a002-a009);
  a010=casadi_sq(a009);
  a008=(a008+a010);
  a010=arg[3]? arg[3][10] : 0;
  a008=(a008-a010);
  if (res[0]!=0) res[0][6]=a008;
  a008=arg[3]? arg[3][11] : 0;
  a008=(a005-a008);
  a010=casadi_sq(a008);
  a011=arg[3]? arg[3][12] : 0;
  a011=(a002-a011);
  a012=casadi_sq(a011);
  a010=(a010+a012);
  a012=arg[3]? arg[3][13] : 0;
  a010=(a010-a012);
  if (res[0]!=0) res[0][7]=a010;
  a010=arg[3]? arg[3][14] : 0;
  a010=(a005-a010);
  a012=casadi_sq(a010);
  a013=arg[3]? arg[3][15] : 0;
  a013=(a002-a013);
  a014=casadi_sq(a013);
  a012=(a012+a014);
  a014=arg[3]? arg[3][16] : 0;
  a012=(a012-a014);
  if (res[0]!=0) res[0][8]=a012;
  a012=arg[3]? arg[3][17] : 0;
  a012=(a005-a012);
  a014=casadi_sq(a012);
  a015=arg[3]? arg[3][18] : 0;
  a015=(a002-a015);
  a016=casadi_sq(a015);
  a014=(a014+a016);
  a016=arg[3]? arg[3][19] : 0;
  a014=(a014-a016);
  if (res[0]!=0) res[0][9]=a014;
  a014=arg[3]? arg[3][20] : 0;
  a014=(a005-a014);
  a016=casadi_sq(a014);
  a017=arg[3]? arg[3][21] : 0;
  a017=(a002-a017);
  a018=casadi_sq(a017);
  a016=(a016+a018);
  a018=arg[3]? arg[3][22] : 0;
  a016=(a016-a018);
  if (res[0]!=0) res[0][10]=a016;
  a016=arg[3]? arg[3][23] : 0;
  a016=(a005-a016);
  a018=casadi_sq(a016);
  a019=arg[3]? arg[3][24] : 0;
  a019=(a002-a019);
  a020=casadi_sq(a019);
  a018=(a018+a020);
  a020=arg[3]? arg[3][25] : 0;
  a018=(a018-a020);
  if (res[0]!=0) res[0][11]=a018;
  a018=arg[3]? arg[3][26] : 0;
  a018=(a005-a018);
  a020=casadi_sq(a018);
  a021=arg[3]? arg[3][27] : 0;
  a021=(a002-a021);
  a022=casadi_sq(a021);
  a020=(a020+a022);
  a022=arg[3]? arg[3][28] : 0;
  a020=(a020-a022);
  if (res[0]!=0) res[0][12]=a020;
  a020=arg[3]? arg[3][29] : 0;
  a020=(a005-a020);
  a022=casadi_sq(a020);
  a023=arg[3]? arg[3][30] : 0;
  a023=(a002-a023);
  a024=casadi_sq(a023);
  a022=(a022+a024);
  a024=arg[3]? arg[3][31] : 0;
  a022=(a022-a024);
  if (res[0]!=0) res[0][13]=a022;
  a022=arg[3]? arg[3][32] : 0;
  a022=(a005-a022);
  a024=casadi_sq(a022);
  a025=arg[3]? arg[3][33] : 0;
  a025=(a002-a025);
  a026=casadi_sq(a025);
  a024=(a024+a026);
  a026=arg[3]? arg[3][34] : 0;
  a024=(a024-a026);
  if (res[0]!=0) res[0][14]=a024;
  a024=arg[3]? arg[3][35] : 0;
  a024=(a005-a024);
  a026=casadi_sq(a024);
  a027=arg[3]? arg[3][36] : 0;
  a027=(a002-a027);
  a028=casadi_sq(a027);
  a026=(a026+a028);
  a028=arg[3]? arg[3][37] : 0;
  a026=(a026-a028);
  if (res[0]!=0) res[0][15]=a026;
  a026=arg[3]? arg[3][38] : 0;
  a028=arg[1]? arg[1][2] : 0;
  a029=(a026*a028);
  a030=arg[3]? arg[3][41] : 0;
  a031=arg[1]? arg[1][3] : 0;
  a032=(a030*a031);
  a029=(a029+a032);
  a032=arg[3]? arg[3][44] : 0;
  a033=arg[1]? arg[1][4] : 0;
  a034=(a032*a033);
  a029=(a029+a034);
  a034=arg[3]? arg[3][47] : 0;
  a035=arg[1]? arg[1][5] : 0;
  a036=(a034*a035);
  a029=(a029+a036);
  a036=arg[3]? arg[3][50] : 0;
  a037=arg[1]? arg[1][6] : 0;
  a038=(a036*a037);
  a029=(a029+a038);
  a038=arg[3]? arg[3][53] : 0;
  a039=arg[1]? arg[1][7] : 0;
  a040=(a038*a039);
  a029=(a029+a040);
  a040=arg[3]? arg[3][56] : 0;
  a041=arg[1]? arg[1][8] : 0;
  a042=(a040*a041);
  a029=(a029+a042);
  a042=arg[3]? arg[3][59] : 0;
  a043=arg[1]? arg[1][9] : 0;
  a044=(a042*a043);
  a029=(a029+a044);
  a044=arg[3]? arg[3][62] : 0;
  a045=arg[1]? arg[1][10] : 0;
  a046=(a044*a045);
  a029=(a029+a046);
  a046=arg[3]? arg[3][65] : 0;
  a047=arg[1]? arg[1][11] : 0;
  a048=(a046*a047);
  a029=(a029+a048);
  a048=arg[3]? arg[3][68] : 0;
  a049=arg[1]? arg[1][12] : 0;
  a050=(a048*a049);
  a029=(a029+a050);
  a050=arg[3]? arg[3][71] : 0;
  a051=arg[1]? arg[1][13] : 0;
  a052=(a050*a051);
  a029=(a029+a052);
  a052=arg[3]? arg[3][74] : 0;
  a053=arg[1]? arg[1][14] : 0;
  a054=(a052*a053);
  a029=(a029+a054);
  a054=arg[3]? arg[3][77] : 0;
  a055=arg[1]? arg[1][15] : 0;
  a056=(a054*a055);
  a029=(a029+a056);
  a056=arg[3]? arg[3][80] : 0;
  a057=arg[1]? arg[1][16] : 0;
  a058=(a056*a057);
  a029=(a029+a058);
  a058=arg[3]? arg[3][83] : 0;
  a059=arg[1]? arg[1][17] : 0;
  a060=(a058*a059);
  a029=(a029+a060);
  a060=arg[3]? arg[3][86] : 0;
  a061=arg[1]? arg[1][18] : 0;
  a062=(a060*a061);
  a029=(a029+a062);
  a062=arg[3]? arg[3][89] : 0;
  a063=arg[1]? arg[1][19] : 0;
  a064=(a062*a063);
  a029=(a029+a064);
  a064=arg[3]? arg[3][92] : 0;
  a065=arg[1]? arg[1][20] : 0;
  a066=(a064*a065);
  a029=(a029+a066);
  a066=arg[3]? arg[3][95] : 0;
  a067=arg[1]? arg[1][21] : 0;
  a068=(a066*a067);
  a029=(a029+a068);
  a068=casadi_sq(a029);
  a069=arg[3]? arg[3][39] : 0;
  a070=(a069*a028);
  a071=arg[3]? arg[3][42] : 0;
  a072=(a071*a031);
  a070=(a070+a072);
  a072=arg[3]? arg[3][45] : 0;
  a073=(a072*a033);
  a070=(a070+a073);
  a073=arg[3]? arg[3][48] : 0;
  a074=(a073*a035);
  a070=(a070+a074);
  a074=arg[3]? arg[3][51] : 0;
  a075=(a074*a037);
  a070=(a070+a075);
  a075=arg[3]? arg[3][54] : 0;
  a076=(a075*a039);
  a070=(a070+a076);
  a076=arg[3]? arg[3][57] : 0;
  a077=(a076*a041);
  a070=(a070+a077);
  a077=arg[3]? arg[3][60] : 0;
  a078=(a077*a043);
  a070=(a070+a078);
  a078=arg[3]? arg[3][63] : 0;
  a079=(a078*a045);
  a070=(a070+a079);
  a079=arg[3]? arg[3][66] : 0;
  a080=(a079*a047);
  a070=(a070+a080);
  a080=arg[3]? arg[3][69] : 0;
  a081=(a080*a049);
  a070=(a070+a081);
  a081=arg[3]? arg[3][72] : 0;
  a082=(a081*a051);
  a070=(a070+a082);
  a082=arg[3]? arg[3][75] : 0;
  a083=(a082*a053);
  a070=(a070+a083);
  a083=arg[3]? arg[3][78] : 0;
  a084=(a083*a055);
  a070=(a070+a084);
  a084=arg[3]? arg[3][81] : 0;
  a085=(a084*a057);
  a070=(a070+a085);
  a085=arg[3]? arg[3][84] : 0;
  a086=(a085*a059);
  a070=(a070+a086);
  a086=arg[3]? arg[3][87] : 0;
  a087=(a086*a061);
  a070=(a070+a087);
  a087=arg[3]? arg[3][90] : 0;
  a088=(a087*a063);
  a070=(a070+a088);
  a088=arg[3]? arg[3][93] : 0;
  a089=(a088*a065);
  a070=(a070+a089);
  a089=arg[3]? arg[3][96] : 0;
  a090=(a089*a067);
  a070=(a070+a090);
  a090=casadi_sq(a070);
  a068=(a068+a090);
  if (res[0]!=0) res[0][16]=a068;
  a068=(a026*a005);
  a090=(a069*a002);
  a068=(a068+a090);
  a090=arg[3]? arg[3][40] : 0;
  a068=(a068-a090);
  a090=(a068*a028);
  if (res[0]!=0) res[0][17]=a090;
  a090=(a030*a005);
  a091=(a071*a002);
  a090=(a090+a091);
  a091=arg[3]? arg[3][43] : 0;
  a090=(a090-a091);
  a091=(a090*a031);
  if (res[0]!=0) res[0][18]=a091;
  a091=(a032*a005);
  a092=(a072*a002);
  a091=(a091+a092);
  a092=arg[3]? arg[3][46] : 0;
  a091=(a091-a092);
  a092=(a091*a033);
  if (res[0]!=0) res[0][19]=a092;
  a092=(a034*a005);
  a093=(a073*a002);
  a092=(a092+a093);
  a093=arg[3]? arg[3][49] : 0;
  a092=(a092-a093);
  a093=(a092*a035);
  if (res[0]!=0) res[0][20]=a093;
  a093=(a036*a005);
  a094=(a074*a002);
  a093=(a093+a094);
  a094=arg[3]? arg[3][52] : 0;
  a093=(a093-a094);
  a094=(a093*a037);
  if (res[0]!=0) res[0][21]=a094;
  a094=(a038*a005);
  a095=(a075*a002);
  a094=(a094+a095);
  a095=arg[3]? arg[3][55] : 0;
  a094=(a094-a095);
  a095=(a094*a039);
  if (res[0]!=0) res[0][22]=a095;
  a095=(a040*a005);
  a096=(a076*a002);
  a095=(a095+a096);
  a096=arg[3]? arg[3][58] : 0;
  a095=(a095-a096);
  a096=(a095*a041);
  if (res[0]!=0) res[0][23]=a096;
  a096=(a042*a005);
  a097=(a077*a002);
  a096=(a096+a097);
  a097=arg[3]? arg[3][61] : 0;
  a096=(a096-a097);
  a097=(a096*a043);
  if (res[0]!=0) res[0][24]=a097;
  a097=(a044*a005);
  a098=(a078*a002);
  a097=(a097+a098);
  a098=arg[3]? arg[3][64] : 0;
  a097=(a097-a098);
  a098=(a097*a045);
  if (res[0]!=0) res[0][25]=a098;
  a098=(a046*a005);
  a099=(a079*a002);
  a098=(a098+a099);
  a099=arg[3]? arg[3][67] : 0;
  a098=(a098-a099);
  a099=(a098*a047);
  if (res[0]!=0) res[0][26]=a099;
  a099=(a048*a005);
  a100=(a080*a002);
  a099=(a099+a100);
  a100=arg[3]? arg[3][70] : 0;
  a099=(a099-a100);
  a100=(a099*a049);
  if (res[0]!=0) res[0][27]=a100;
  a100=(a050*a005);
  a101=(a081*a002);
  a100=(a100+a101);
  a101=arg[3]? arg[3][73] : 0;
  a100=(a100-a101);
  a101=(a100*a051);
  if (res[0]!=0) res[0][28]=a101;
  a101=(a052*a005);
  a102=(a082*a002);
  a101=(a101+a102);
  a102=arg[3]? arg[3][76] : 0;
  a101=(a101-a102);
  a102=(a101*a053);
  if (res[0]!=0) res[0][29]=a102;
  a102=(a054*a005);
  a103=(a083*a002);
  a102=(a102+a103);
  a103=arg[3]? arg[3][79] : 0;
  a102=(a102-a103);
  a103=(a102*a055);
  if (res[0]!=0) res[0][30]=a103;
  a103=(a056*a005);
  a104=(a084*a002);
  a103=(a103+a104);
  a104=arg[3]? arg[3][82] : 0;
  a103=(a103-a104);
  a104=(a103*a057);
  if (res[0]!=0) res[0][31]=a104;
  a104=(a058*a005);
  a105=(a085*a002);
  a104=(a104+a105);
  a105=arg[3]? arg[3][85] : 0;
  a104=(a104-a105);
  a105=(a104*a059);
  if (res[0]!=0) res[0][32]=a105;
  a105=(a060*a005);
  a106=(a086*a002);
  a105=(a105+a106);
  a106=arg[3]? arg[3][88] : 0;
  a105=(a105-a106);
  a106=(a105*a061);
  if (res[0]!=0) res[0][33]=a106;
  a106=(a062*a005);
  a107=(a087*a002);
  a106=(a106+a107);
  a107=arg[3]? arg[3][91] : 0;
  a106=(a106-a107);
  a107=(a106*a063);
  if (res[0]!=0) res[0][34]=a107;
  a107=(a064*a005);
  a108=(a088*a002);
  a107=(a107+a108);
  a108=arg[3]? arg[3][94] : 0;
  a107=(a107-a108);
  a108=(a107*a065);
  if (res[0]!=0) res[0][35]=a108;
  a005=(a066*a005);
  a002=(a089*a002);
  a005=(a005+a002);
  a002=arg[3]? arg[3][97] : 0;
  a005=(a005-a002);
  a002=(a005*a067);
  if (res[0]!=0) res[0][36]=a002;
  a002=1.;
  if (res[1]!=0) res[1][0]=a002;
  a108=-2.9999999999999999e-01;
  if (res[1]!=0) res[1][1]=a108;
  if (res[1]!=0) res[1][2]=a002;
  if (res[1]!=0) res[1][3]=a001;
  if (res[1]!=0) res[1][4]=a002;
  if (res[1]!=0) res[1][5]=a108;
  if (res[1]!=0) res[1][6]=a002;
  if (res[1]!=0) res[1][7]=a001;
  a004=(-a004);
  if (res[1]!=0) res[1][8]=a004;
  if (res[1]!=0) res[1][9]=a000;
  a007=(-a007);
  if (res[1]!=0) res[1][10]=a007;
  if (res[1]!=0) res[1][11]=a003;
  a006=(a006+a006);
  if (res[1]!=0) res[1][12]=a006;
  a009=(a009+a009);
  if (res[1]!=0) res[1][13]=a009;
  a008=(a008+a008);
  if (res[1]!=0) res[1][14]=a008;
  a011=(a011+a011);
  if (res[1]!=0) res[1][15]=a011;
  a010=(a010+a010);
  if (res[1]!=0) res[1][16]=a010;
  a013=(a013+a013);
  if (res[1]!=0) res[1][17]=a013;
  a012=(a012+a012);
  if (res[1]!=0) res[1][18]=a012;
  a015=(a015+a015);
  if (res[1]!=0) res[1][19]=a015;
  a014=(a014+a014);
  if (res[1]!=0) res[1][20]=a014;
  a017=(a017+a017);
  if (res[1]!=0) res[1][21]=a017;
  a016=(a016+a016);
  if (res[1]!=0) res[1][22]=a016;
  a019=(a019+a019);
  if (res[1]!=0) res[1][23]=a019;
  a018=(a018+a018);
  if (res[1]!=0) res[1][24]=a018;
  a021=(a021+a021);
  if (res[1]!=0) res[1][25]=a021;
  a020=(a020+a020);
  if (res[1]!=0) res[1][26]=a020;
  a023=(a023+a023);
  if (res[1]!=0) res[1][27]=a023;
  a022=(a022+a022);
  if (res[1]!=0) res[1][28]=a022;
  a025=(a025+a025);
  if (res[1]!=0) res[1][29]=a025;
  a024=(a024+a024);
  if (res[1]!=0) res[1][30]=a024;
  a027=(a027+a027);
  if (res[1]!=0) res[1][31]=a027;
  a029=(a029+a029);
  a027=(a029*a026);
  a070=(a070+a070);
  a024=(a070*a069);
  a027=(a027+a024);
  if (res[1]!=0) res[1][32]=a027;
  a027=(a029*a030);
  a024=(a070*a071);
  a027=(a027+a024);
  if (res[1]!=0) res[1][33]=a027;
  a027=(a029*a032);
  a024=(a070*a072);
  a027=(a027+a024);
  if (res[1]!=0) res[1][34]=a027;
  a027=(a029*a034);
  a024=(a070*a073);
  a027=(a027+a024);
  if (res[1]!=0) res[1][35]=a027;
  a027=(a029*a036);
  a024=(a070*a074);
  a027=(a027+a024);
  if (res[1]!=0) res[1][36]=a027;
  a027=(a029*a038);
  a024=(a070*a075);
  a027=(a027+a024);
  if (res[1]!=0) res[1][37]=a027;
  a027=(a029*a040);
  a024=(a070*a076);
  a027=(a027+a024);
  if (res[1]!=0) res[1][38]=a027;
  a027=(a029*a042);
  a024=(a070*a077);
  a027=(a027+a024);
  if (res[1]!=0) res[1][39]=a027;
  a027=(a029*a044);
  a024=(a070*a078);
  a027=(a027+a024);
  if (res[1]!=0) res[1][40]=a027;
  a027=(a029*a046);
  a024=(a070*a079);
  a027=(a027+a024);
  if (res[1]!=0) res[1][41]=a027;
  a027=(a029*a048);
  a024=(a070*a080);
  a027=(a027+a024);
  if (res[1]!=0) res[1][42]=a027;
  a027=(a029*a050);
  a024=(a070*a081);
  a027=(a027+a024);
  if (res[1]!=0) res[1][43]=a027;
  a027=(a029*a052);
  a024=(a070*a082);
  a027=(a027+a024);
  if (res[1]!=0) res[1][44]=a027;
  a027=(a029*a054);
  a024=(a070*a083);
  a027=(a027+a024);
  if (res[1]!=0) res[1][45]=a027;
  a027=(a029*a056);
  a024=(a070*a084);
  a027=(a027+a024);
  if (res[1]!=0) res[1][46]=a027;
  a027=(a029*a058);
  a024=(a070*a085);
  a027=(a027+a024);
  if (res[1]!=0) res[1][47]=a027;
  a027=(a029*a060);
  a024=(a070*a086);
  a027=(a027+a024);
  if (res[1]!=0) res[1][48]=a027;
  a027=(a029*a062);
  a024=(a070*a087);
  a027=(a027+a024);
  if (res[1]!=0) res[1][49]=a027;
  a027=(a029*a064);
  a024=(a070*a088);
  a027=(a027+a024);
  if (res[1]!=0) res[1][50]=a027;
  a029=(a029*a066);
  a070=(a070*a089);
  a029=(a029+a070);
  if (res[1]!=0) res[1][51]=a029;
  if (res[1]!=0) res[1][52]=a068;
  a026=(a028*a026);
  if (res[1]!=0) res[1][53]=a026;
  a028=(a028*a069);
  if (res[1]!=0) res[1][54]=a028;
  if (res[1]!=0) res[1][55]=a090;
  a030=(a031*a030);
  if (res[1]!=0) res[1][56]=a030;
  a031=(a031*a071);
  if (res[1]!=0) res[1][57]=a031;
  if (res[1]!=0) res[1][58]=a091;
  a032=(a033*a032);
  if (res[1]!=0) res[1][59]=a032;
  a033=(a033*a072);
  if (res[1]!=0) res[1][60]=a033;
  if (res[1]!=0) res[1][61]=a092;
  a034=(a035*a034);
  if (res[1]!=0) res[1][62]=a034;
  a035=(a035*a073);
  if (res[1]!=0) res[1][63]=a035;
  if (res[1]!=0) res[1][64]=a093;
  a036=(a037*a036);
  if (res[1]!=0) res[1][65]=a036;
  a037=(a037*a074);
  if (res[1]!=0) res[1][66]=a037;
  if (res[1]!=0) res[1][67]=a094;
  a038=(a039*a038);
  if (res[1]!=0) res[1][68]=a038;
  a039=(a039*a075);
  if (res[1]!=0) res[1][69]=a039;
  if (res[1]!=0) res[1][70]=a095;
  a040=(a041*a040);
  if (res[1]!=0) res[1][71]=a040;
  a041=(a041*a076);
  if (res[1]!=0) res[1][72]=a041;
  if (res[1]!=0) res[1][73]=a096;
  a042=(a043*a042);
  if (res[1]!=0) res[1][74]=a042;
  a043=(a043*a077);
  if (res[1]!=0) res[1][75]=a043;
  if (res[1]!=0) res[1][76]=a097;
  a044=(a045*a044);
  if (res[1]!=0) res[1][77]=a044;
  a045=(a045*a078);
  if (res[1]!=0) res[1][78]=a045;
  if (res[1]!=0) res[1][79]=a098;
  a046=(a047*a046);
  if (res[1]!=0) res[1][80]=a046;
  a047=(a047*a079);
  if (res[1]!=0) res[1][81]=a047;
  if (res[1]!=0) res[1][82]=a099;
  a048=(a049*a048);
  if (res[1]!=0) res[1][83]=a048;
  a049=(a049*a080);
  if (res[1]!=0) res[1][84]=a049;
  if (res[1]!=0) res[1][85]=a100;
  a050=(a051*a050);
  if (res[1]!=0) res[1][86]=a050;
  a051=(a051*a081);
  if (res[1]!=0) res[1][87]=a051;
  if (res[1]!=0) res[1][88]=a101;
  a052=(a053*a052);
  if (res[1]!=0) res[1][89]=a052;
  a053=(a053*a082);
  if (res[1]!=0) res[1][90]=a053;
  if (res[1]!=0) res[1][91]=a102;
  a054=(a055*a054);
  if (res[1]!=0) res[1][92]=a054;
  a055=(a055*a083);
  if (res[1]!=0) res[1][93]=a055;
  if (res[1]!=0) res[1][94]=a103;
  a056=(a057*a056);
  if (res[1]!=0) res[1][95]=a056;
  a057=(a057*a084);
  if (res[1]!=0) res[1][96]=a057;
  if (res[1]!=0) res[1][97]=a104;
  a058=(a059*a058);
  if (res[1]!=0) res[1][98]=a058;
  a059=(a059*a085);
  if (res[1]!=0) res[1][99]=a059;
  if (res[1]!=0) res[1][100]=a105;
  a060=(a061*a060);
  if (res[1]!=0) res[1][101]=a060;
  a061=(a061*a086);
  if (res[1]!=0) res[1][102]=a061;
  if (res[1]!=0) res[1][103]=a106;
  a062=(a063*a062);
  if (res[1]!=0) res[1][104]=a062;
  a063=(a063*a087);
  if (res[1]!=0) res[1][105]=a063;
  if (res[1]!=0) res[1][106]=a107;
  a064=(a065*a064);
  if (res[1]!=0) res[1][107]=a064;
  a065=(a065*a088);
  if (res[1]!=0) res[1][108]=a065;
  if (res[1]!=0) res[1][109]=a005;
  a066=(a067*a066);
  if (res[1]!=0) res[1][110]=a066;
  a067=(a067*a089);
  if (res[1]!=0) res[1][111]=a067;
  return 0;
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_jac_uxt_zt(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_jac_uxt_zt_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_jac_uxt_zt_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ddmr_constr_h_fun_jac_uxt_zt_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_jac_uxt_zt_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ddmr_constr_h_fun_jac_uxt_zt_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ddmr_constr_h_fun_jac_uxt_zt_incref(void) {
}

CASADI_SYMBOL_EXPORT void ddmr_constr_h_fun_jac_uxt_zt_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ddmr_constr_h_fun_jac_uxt_zt_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int ddmr_constr_h_fun_jac_uxt_zt_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real ddmr_constr_h_fun_jac_uxt_zt_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ddmr_constr_h_fun_jac_uxt_zt_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ddmr_constr_h_fun_jac_uxt_zt_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ddmr_constr_h_fun_jac_uxt_zt_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ddmr_constr_h_fun_jac_uxt_zt_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_jac_uxt_zt_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ddmr_constr_h_fun_jac_uxt_zt_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
