amr_interfaces/JointState ob
amr_interfaces/Point sub_goal

---
bool success
float64 al
float64 ar
amr_interfaces/Point revised_goal
amr_interfaces/Point[] astar_path
amr_interfaces/ControlVar[] control_vars