/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ddmr_expl_vde_forw_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[3] = {7, 1, 1};
static const casadi_int casadi_s1[3] = {7, 7, 1};
static const casadi_int casadi_s2[3] = {7, 22, 1};
static const casadi_int casadi_s3[3] = {22, 1, 1};
static const casadi_int casadi_s4[3] = {98, 1, 1};

/* ddmr_expl_vde_forw:(i0[7],i1[7x7],i2[7x22],i3[22],i4[98])->(o0[7],o1[7x7],o2[7x22]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=arg[0]? arg[0][3] : 0;
  a1=arg[0]? arg[0][2] : 0;
  a2=cos(a1);
  a3=(a0*a2);
  if (res[0]!=0) res[0][0]=a3;
  a1=sin(a1);
  a3=(a0*a1);
  if (res[0]!=0) res[0][1]=a3;
  a3=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][2]=a3;
  a3=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][3]=a3;
  a3=arg[0]? arg[0][6] : 0;
  if (res[0]!=0) res[0][4]=a3;
  a3=arg[3]? arg[3][0] : 0;
  if (res[0]!=0) res[0][5]=a3;
  a3=arg[3]? arg[3][1] : 0;
  if (res[0]!=0) res[0][6]=a3;
  a3=arg[1]? arg[1][3] : 0;
  a4=(a2*a3);
  a5=arg[1]? arg[1][2] : 0;
  a6=(a1*a5);
  a6=(a0*a6);
  a4=(a4-a6);
  if (res[1]!=0) res[1][0]=a4;
  a3=(a1*a3);
  a5=(a2*a5);
  a5=(a0*a5);
  a3=(a3+a5);
  if (res[1]!=0) res[1][1]=a3;
  a3=arg[1]? arg[1][4] : 0;
  if (res[1]!=0) res[1][2]=a3;
  a3=arg[1]? arg[1][5] : 0;
  if (res[1]!=0) res[1][3]=a3;
  a3=arg[1]? arg[1][6] : 0;
  if (res[1]!=0) res[1][4]=a3;
  a3=0.;
  if (res[1]!=0) res[1][5]=a3;
  if (res[1]!=0) res[1][6]=a3;
  a5=arg[1]? arg[1][10] : 0;
  a4=(a2*a5);
  a6=arg[1]? arg[1][9] : 0;
  a7=(a1*a6);
  a7=(a0*a7);
  a4=(a4-a7);
  if (res[1]!=0) res[1][7]=a4;
  a5=(a1*a5);
  a6=(a2*a6);
  a6=(a0*a6);
  a5=(a5+a6);
  if (res[1]!=0) res[1][8]=a5;
  a5=arg[1]? arg[1][11] : 0;
  if (res[1]!=0) res[1][9]=a5;
  a5=arg[1]? arg[1][12] : 0;
  if (res[1]!=0) res[1][10]=a5;
  a5=arg[1]? arg[1][13] : 0;
  if (res[1]!=0) res[1][11]=a5;
  if (res[1]!=0) res[1][12]=a3;
  if (res[1]!=0) res[1][13]=a3;
  a5=arg[1]? arg[1][17] : 0;
  a6=(a2*a5);
  a4=arg[1]? arg[1][16] : 0;
  a7=(a1*a4);
  a7=(a0*a7);
  a6=(a6-a7);
  if (res[1]!=0) res[1][14]=a6;
  a5=(a1*a5);
  a4=(a2*a4);
  a4=(a0*a4);
  a5=(a5+a4);
  if (res[1]!=0) res[1][15]=a5;
  a5=arg[1]? arg[1][18] : 0;
  if (res[1]!=0) res[1][16]=a5;
  a5=arg[1]? arg[1][19] : 0;
  if (res[1]!=0) res[1][17]=a5;
  a5=arg[1]? arg[1][20] : 0;
  if (res[1]!=0) res[1][18]=a5;
  if (res[1]!=0) res[1][19]=a3;
  if (res[1]!=0) res[1][20]=a3;
  a5=arg[1]? arg[1][24] : 0;
  a4=(a2*a5);
  a6=arg[1]? arg[1][23] : 0;
  a7=(a1*a6);
  a7=(a0*a7);
  a4=(a4-a7);
  if (res[1]!=0) res[1][21]=a4;
  a5=(a1*a5);
  a6=(a2*a6);
  a6=(a0*a6);
  a5=(a5+a6);
  if (res[1]!=0) res[1][22]=a5;
  a5=arg[1]? arg[1][25] : 0;
  if (res[1]!=0) res[1][23]=a5;
  a5=arg[1]? arg[1][26] : 0;
  if (res[1]!=0) res[1][24]=a5;
  a5=arg[1]? arg[1][27] : 0;
  if (res[1]!=0) res[1][25]=a5;
  if (res[1]!=0) res[1][26]=a3;
  if (res[1]!=0) res[1][27]=a3;
  a5=arg[1]? arg[1][31] : 0;
  a6=(a2*a5);
  a4=arg[1]? arg[1][30] : 0;
  a7=(a1*a4);
  a7=(a0*a7);
  a6=(a6-a7);
  if (res[1]!=0) res[1][28]=a6;
  a5=(a1*a5);
  a4=(a2*a4);
  a4=(a0*a4);
  a5=(a5+a4);
  if (res[1]!=0) res[1][29]=a5;
  a5=arg[1]? arg[1][32] : 0;
  if (res[1]!=0) res[1][30]=a5;
  a5=arg[1]? arg[1][33] : 0;
  if (res[1]!=0) res[1][31]=a5;
  a5=arg[1]? arg[1][34] : 0;
  if (res[1]!=0) res[1][32]=a5;
  if (res[1]!=0) res[1][33]=a3;
  if (res[1]!=0) res[1][34]=a3;
  a5=arg[1]? arg[1][38] : 0;
  a4=(a2*a5);
  a6=arg[1]? arg[1][37] : 0;
  a7=(a1*a6);
  a7=(a0*a7);
  a4=(a4-a7);
  if (res[1]!=0) res[1][35]=a4;
  a5=(a1*a5);
  a6=(a2*a6);
  a6=(a0*a6);
  a5=(a5+a6);
  if (res[1]!=0) res[1][36]=a5;
  a5=arg[1]? arg[1][39] : 0;
  if (res[1]!=0) res[1][37]=a5;
  a5=arg[1]? arg[1][40] : 0;
  if (res[1]!=0) res[1][38]=a5;
  a5=arg[1]? arg[1][41] : 0;
  if (res[1]!=0) res[1][39]=a5;
  if (res[1]!=0) res[1][40]=a3;
  if (res[1]!=0) res[1][41]=a3;
  a5=arg[1]? arg[1][45] : 0;
  a6=(a2*a5);
  a4=arg[1]? arg[1][44] : 0;
  a7=(a1*a4);
  a7=(a0*a7);
  a6=(a6-a7);
  if (res[1]!=0) res[1][42]=a6;
  a5=(a1*a5);
  a4=(a2*a4);
  a4=(a0*a4);
  a5=(a5+a4);
  if (res[1]!=0) res[1][43]=a5;
  a5=arg[1]? arg[1][46] : 0;
  if (res[1]!=0) res[1][44]=a5;
  a5=arg[1]? arg[1][47] : 0;
  if (res[1]!=0) res[1][45]=a5;
  a5=arg[1]? arg[1][48] : 0;
  if (res[1]!=0) res[1][46]=a5;
  if (res[1]!=0) res[1][47]=a3;
  if (res[1]!=0) res[1][48]=a3;
  a5=arg[2]? arg[2][3] : 0;
  a4=(a2*a5);
  a6=arg[2]? arg[2][2] : 0;
  a7=(a1*a6);
  a7=(a0*a7);
  a4=(a4-a7);
  if (res[2]!=0) res[2][0]=a4;
  a5=(a1*a5);
  a6=(a2*a6);
  a6=(a0*a6);
  a5=(a5+a6);
  if (res[2]!=0) res[2][1]=a5;
  a5=arg[2]? arg[2][4] : 0;
  if (res[2]!=0) res[2][2]=a5;
  a5=arg[2]? arg[2][5] : 0;
  if (res[2]!=0) res[2][3]=a5;
  a5=arg[2]? arg[2][6] : 0;
  if (res[2]!=0) res[2][4]=a5;
  a5=1.;
  if (res[2]!=0) res[2][5]=a5;
  if (res[2]!=0) res[2][6]=a3;
  a6=arg[2]? arg[2][10] : 0;
  a4=(a2*a6);
  a7=arg[2]? arg[2][9] : 0;
  a8=(a1*a7);
  a8=(a0*a8);
  a4=(a4-a8);
  if (res[2]!=0) res[2][7]=a4;
  a6=(a1*a6);
  a7=(a2*a7);
  a7=(a0*a7);
  a6=(a6+a7);
  if (res[2]!=0) res[2][8]=a6;
  a6=arg[2]? arg[2][11] : 0;
  if (res[2]!=0) res[2][9]=a6;
  a6=arg[2]? arg[2][12] : 0;
  if (res[2]!=0) res[2][10]=a6;
  a6=arg[2]? arg[2][13] : 0;
  if (res[2]!=0) res[2][11]=a6;
  if (res[2]!=0) res[2][12]=a3;
  if (res[2]!=0) res[2][13]=a5;
  a5=arg[2]? arg[2][17] : 0;
  a6=(a2*a5);
  a7=arg[2]? arg[2][16] : 0;
  a4=(a1*a7);
  a4=(a0*a4);
  a6=(a6-a4);
  if (res[2]!=0) res[2][14]=a6;
  a5=(a1*a5);
  a7=(a2*a7);
  a7=(a0*a7);
  a5=(a5+a7);
  if (res[2]!=0) res[2][15]=a5;
  a5=arg[2]? arg[2][18] : 0;
  if (res[2]!=0) res[2][16]=a5;
  a5=arg[2]? arg[2][19] : 0;
  if (res[2]!=0) res[2][17]=a5;
  a5=arg[2]? arg[2][20] : 0;
  if (res[2]!=0) res[2][18]=a5;
  if (res[2]!=0) res[2][19]=a3;
  if (res[2]!=0) res[2][20]=a3;
  a5=arg[2]? arg[2][24] : 0;
  a7=(a2*a5);
  a6=arg[2]? arg[2][23] : 0;
  a4=(a1*a6);
  a4=(a0*a4);
  a7=(a7-a4);
  if (res[2]!=0) res[2][21]=a7;
  a5=(a1*a5);
  a6=(a2*a6);
  a6=(a0*a6);
  a5=(a5+a6);
  if (res[2]!=0) res[2][22]=a5;
  a5=arg[2]? arg[2][25] : 0;
  if (res[2]!=0) res[2][23]=a5;
  a5=arg[2]? arg[2][26] : 0;
  if (res[2]!=0) res[2][24]=a5;
  a5=arg[2]? arg[2][27] : 0;
  if (res[2]!=0) res[2][25]=a5;
  if (res[2]!=0) res[2][26]=a3;
  if (res[2]!=0) res[2][27]=a3;
  a5=arg[2]? arg[2][31] : 0;
  a6=(a2*a5);
  a7=arg[2]? arg[2][30] : 0;
  a4=(a1*a7);
  a4=(a0*a4);
  a6=(a6-a4);
  if (res[2]!=0) res[2][28]=a6;
  a5=(a1*a5);
  a7=(a2*a7);
  a7=(a0*a7);
  a5=(a5+a7);
  if (res[2]!=0) res[2][29]=a5;
  a5=arg[2]? arg[2][32] : 0;
  if (res[2]!=0) res[2][30]=a5;
  a5=arg[2]? arg[2][33] : 0;
  if (res[2]!=0) res[2][31]=a5;
  a5=arg[2]? arg[2][34] : 0;
  if (res[2]!=0) res[2][32]=a5;
  if (res[2]!=0) res[2][33]=a3;
  if (res[2]!=0) res[2][34]=a3;
  a5=arg[2]? arg[2][38] : 0;
  a7=(a2*a5);
  a6=arg[2]? arg[2][37] : 0;
  a4=(a1*a6);
  a4=(a0*a4);
  a7=(a7-a4);
  if (res[2]!=0) res[2][35]=a7;
  a5=(a1*a5);
  a6=(a2*a6);
  a6=(a0*a6);
  a5=(a5+a6);
  if (res[2]!=0) res[2][36]=a5;
  a5=arg[2]? arg[2][39] : 0;
  if (res[2]!=0) res[2][37]=a5;
  a5=arg[2]? arg[2][40] : 0;
  if (res[2]!=0) res[2][38]=a5;
  a5=arg[2]? arg[2][41] : 0;
  if (res[2]!=0) res[2][39]=a5;
  if (res[2]!=0) res[2][40]=a3;
  if (res[2]!=0) res[2][41]=a3;
  a5=arg[2]? arg[2][45] : 0;
  a6=(a2*a5);
  a7=arg[2]? arg[2][44] : 0;
  a4=(a1*a7);
  a4=(a0*a4);
  a6=(a6-a4);
  if (res[2]!=0) res[2][42]=a6;
  a5=(a1*a5);
  a7=(a2*a7);
  a7=(a0*a7);
  a5=(a5+a7);
  if (res[2]!=0) res[2][43]=a5;
  a5=arg[2]? arg[2][46] : 0;
  if (res[2]!=0) res[2][44]=a5;
  a5=arg[2]? arg[2][47] : 0;
  if (res[2]!=0) res[2][45]=a5;
  a5=arg[2]? arg[2][48] : 0;
  if (res[2]!=0) res[2][46]=a5;
  if (res[2]!=0) res[2][47]=a3;
  if (res[2]!=0) res[2][48]=a3;
  a5=arg[2]? arg[2][52] : 0;
  a7=(a2*a5);
  a6=arg[2]? arg[2][51] : 0;
  a4=(a1*a6);
  a4=(a0*a4);
  a7=(a7-a4);
  if (res[2]!=0) res[2][49]=a7;
  a5=(a1*a5);
  a6=(a2*a6);
  a6=(a0*a6);
  a5=(a5+a6);
  if (res[2]!=0) res[2][50]=a5;
  a5=arg[2]? arg[2][53] : 0;
  if (res[2]!=0) res[2][51]=a5;
  a5=arg[2]? arg[2][54] : 0;
  if (res[2]!=0) res[2][52]=a5;
  a5=arg[2]? arg[2][55] : 0;
  if (res[2]!=0) res[2][53]=a5;
  if (res[2]!=0) res[2][54]=a3;
  if (res[2]!=0) res[2][55]=a3;
  a5=arg[2]? arg[2][59] : 0;
  a6=(a2*a5);
  a7=arg[2]? arg[2][58] : 0;
  a4=(a1*a7);
  a4=(a0*a4);
  a6=(a6-a4);
  if (res[2]!=0) res[2][56]=a6;
  a5=(a1*a5);
  a7=(a2*a7);
  a7=(a0*a7);
  a5=(a5+a7);
  if (res[2]!=0) res[2][57]=a5;
  a5=arg[2]? arg[2][60] : 0;
  if (res[2]!=0) res[2][58]=a5;
  a5=arg[2]? arg[2][61] : 0;
  if (res[2]!=0) res[2][59]=a5;
  a5=arg[2]? arg[2][62] : 0;
  if (res[2]!=0) res[2][60]=a5;
  if (res[2]!=0) res[2][61]=a3;
  if (res[2]!=0) res[2][62]=a3;
  a5=arg[2]? arg[2][66] : 0;
  a7=(a2*a5);
  a6=arg[2]? arg[2][65] : 0;
  a4=(a1*a6);
  a4=(a0*a4);
  a7=(a7-a4);
  if (res[2]!=0) res[2][63]=a7;
  a5=(a1*a5);
  a6=(a2*a6);
  a6=(a0*a6);
  a5=(a5+a6);
  if (res[2]!=0) res[2][64]=a5;
  a5=arg[2]? arg[2][67] : 0;
  if (res[2]!=0) res[2][65]=a5;
  a5=arg[2]? arg[2][68] : 0;
  if (res[2]!=0) res[2][66]=a5;
  a5=arg[2]? arg[2][69] : 0;
  if (res[2]!=0) res[2][67]=a5;
  if (res[2]!=0) res[2][68]=a3;
  if (res[2]!=0) res[2][69]=a3;
  a5=arg[2]? arg[2][73] : 0;
  a6=(a2*a5);
  a7=arg[2]? arg[2][72] : 0;
  a4=(a1*a7);
  a4=(a0*a4);
  a6=(a6-a4);
  if (res[2]!=0) res[2][70]=a6;
  a5=(a1*a5);
  a7=(a2*a7);
  a7=(a0*a7);
  a5=(a5+a7);
  if (res[2]!=0) res[2][71]=a5;
  a5=arg[2]? arg[2][74] : 0;
  if (res[2]!=0) res[2][72]=a5;
  a5=arg[2]? arg[2][75] : 0;
  if (res[2]!=0) res[2][73]=a5;
  a5=arg[2]? arg[2][76] : 0;
  if (res[2]!=0) res[2][74]=a5;
  if (res[2]!=0) res[2][75]=a3;
  if (res[2]!=0) res[2][76]=a3;
  a5=arg[2]? arg[2][80] : 0;
  a7=(a2*a5);
  a6=arg[2]? arg[2][79] : 0;
  a4=(a1*a6);
  a4=(a0*a4);
  a7=(a7-a4);
  if (res[2]!=0) res[2][77]=a7;
  a5=(a1*a5);
  a6=(a2*a6);
  a6=(a0*a6);
  a5=(a5+a6);
  if (res[2]!=0) res[2][78]=a5;
  a5=arg[2]? arg[2][81] : 0;
  if (res[2]!=0) res[2][79]=a5;
  a5=arg[2]? arg[2][82] : 0;
  if (res[2]!=0) res[2][80]=a5;
  a5=arg[2]? arg[2][83] : 0;
  if (res[2]!=0) res[2][81]=a5;
  if (res[2]!=0) res[2][82]=a3;
  if (res[2]!=0) res[2][83]=a3;
  a5=arg[2]? arg[2][87] : 0;
  a6=(a2*a5);
  a7=arg[2]? arg[2][86] : 0;
  a4=(a1*a7);
  a4=(a0*a4);
  a6=(a6-a4);
  if (res[2]!=0) res[2][84]=a6;
  a5=(a1*a5);
  a7=(a2*a7);
  a7=(a0*a7);
  a5=(a5+a7);
  if (res[2]!=0) res[2][85]=a5;
  a5=arg[2]? arg[2][88] : 0;
  if (res[2]!=0) res[2][86]=a5;
  a5=arg[2]? arg[2][89] : 0;
  if (res[2]!=0) res[2][87]=a5;
  a5=arg[2]? arg[2][90] : 0;
  if (res[2]!=0) res[2][88]=a5;
  if (res[2]!=0) res[2][89]=a3;
  if (res[2]!=0) res[2][90]=a3;
  a5=arg[2]? arg[2][94] : 0;
  a7=(a2*a5);
  a6=arg[2]? arg[2][93] : 0;
  a4=(a1*a6);
  a4=(a0*a4);
  a7=(a7-a4);
  if (res[2]!=0) res[2][91]=a7;
  a5=(a1*a5);
  a6=(a2*a6);
  a6=(a0*a6);
  a5=(a5+a6);
  if (res[2]!=0) res[2][92]=a5;
  a5=arg[2]? arg[2][95] : 0;
  if (res[2]!=0) res[2][93]=a5;
  a5=arg[2]? arg[2][96] : 0;
  if (res[2]!=0) res[2][94]=a5;
  a5=arg[2]? arg[2][97] : 0;
  if (res[2]!=0) res[2][95]=a5;
  if (res[2]!=0) res[2][96]=a3;
  if (res[2]!=0) res[2][97]=a3;
  a5=arg[2]? arg[2][101] : 0;
  a6=(a2*a5);
  a7=arg[2]? arg[2][100] : 0;
  a4=(a1*a7);
  a4=(a0*a4);
  a6=(a6-a4);
  if (res[2]!=0) res[2][98]=a6;
  a5=(a1*a5);
  a7=(a2*a7);
  a7=(a0*a7);
  a5=(a5+a7);
  if (res[2]!=0) res[2][99]=a5;
  a5=arg[2]? arg[2][102] : 0;
  if (res[2]!=0) res[2][100]=a5;
  a5=arg[2]? arg[2][103] : 0;
  if (res[2]!=0) res[2][101]=a5;
  a5=arg[2]? arg[2][104] : 0;
  if (res[2]!=0) res[2][102]=a5;
  if (res[2]!=0) res[2][103]=a3;
  if (res[2]!=0) res[2][104]=a3;
  a5=arg[2]? arg[2][108] : 0;
  a7=(a2*a5);
  a6=arg[2]? arg[2][107] : 0;
  a4=(a1*a6);
  a4=(a0*a4);
  a7=(a7-a4);
  if (res[2]!=0) res[2][105]=a7;
  a5=(a1*a5);
  a6=(a2*a6);
  a6=(a0*a6);
  a5=(a5+a6);
  if (res[2]!=0) res[2][106]=a5;
  a5=arg[2]? arg[2][109] : 0;
  if (res[2]!=0) res[2][107]=a5;
  a5=arg[2]? arg[2][110] : 0;
  if (res[2]!=0) res[2][108]=a5;
  a5=arg[2]? arg[2][111] : 0;
  if (res[2]!=0) res[2][109]=a5;
  if (res[2]!=0) res[2][110]=a3;
  if (res[2]!=0) res[2][111]=a3;
  a5=arg[2]? arg[2][115] : 0;
  a6=(a2*a5);
  a7=arg[2]? arg[2][114] : 0;
  a4=(a1*a7);
  a4=(a0*a4);
  a6=(a6-a4);
  if (res[2]!=0) res[2][112]=a6;
  a5=(a1*a5);
  a7=(a2*a7);
  a7=(a0*a7);
  a5=(a5+a7);
  if (res[2]!=0) res[2][113]=a5;
  a5=arg[2]? arg[2][116] : 0;
  if (res[2]!=0) res[2][114]=a5;
  a5=arg[2]? arg[2][117] : 0;
  if (res[2]!=0) res[2][115]=a5;
  a5=arg[2]? arg[2][118] : 0;
  if (res[2]!=0) res[2][116]=a5;
  if (res[2]!=0) res[2][117]=a3;
  if (res[2]!=0) res[2][118]=a3;
  a5=arg[2]? arg[2][122] : 0;
  a7=(a2*a5);
  a6=arg[2]? arg[2][121] : 0;
  a4=(a1*a6);
  a4=(a0*a4);
  a7=(a7-a4);
  if (res[2]!=0) res[2][119]=a7;
  a5=(a1*a5);
  a6=(a2*a6);
  a6=(a0*a6);
  a5=(a5+a6);
  if (res[2]!=0) res[2][120]=a5;
  a5=arg[2]? arg[2][123] : 0;
  if (res[2]!=0) res[2][121]=a5;
  a5=arg[2]? arg[2][124] : 0;
  if (res[2]!=0) res[2][122]=a5;
  a5=arg[2]? arg[2][125] : 0;
  if (res[2]!=0) res[2][123]=a5;
  if (res[2]!=0) res[2][124]=a3;
  if (res[2]!=0) res[2][125]=a3;
  a5=arg[2]? arg[2][129] : 0;
  a6=(a2*a5);
  a7=arg[2]? arg[2][128] : 0;
  a4=(a1*a7);
  a4=(a0*a4);
  a6=(a6-a4);
  if (res[2]!=0) res[2][126]=a6;
  a5=(a1*a5);
  a7=(a2*a7);
  a7=(a0*a7);
  a5=(a5+a7);
  if (res[2]!=0) res[2][127]=a5;
  a5=arg[2]? arg[2][130] : 0;
  if (res[2]!=0) res[2][128]=a5;
  a5=arg[2]? arg[2][131] : 0;
  if (res[2]!=0) res[2][129]=a5;
  a5=arg[2]? arg[2][132] : 0;
  if (res[2]!=0) res[2][130]=a5;
  if (res[2]!=0) res[2][131]=a3;
  if (res[2]!=0) res[2][132]=a3;
  a5=arg[2]? arg[2][136] : 0;
  a7=(a2*a5);
  a6=arg[2]? arg[2][135] : 0;
  a4=(a1*a6);
  a4=(a0*a4);
  a7=(a7-a4);
  if (res[2]!=0) res[2][133]=a7;
  a5=(a1*a5);
  a6=(a2*a6);
  a6=(a0*a6);
  a5=(a5+a6);
  if (res[2]!=0) res[2][134]=a5;
  a5=arg[2]? arg[2][137] : 0;
  if (res[2]!=0) res[2][135]=a5;
  a5=arg[2]? arg[2][138] : 0;
  if (res[2]!=0) res[2][136]=a5;
  a5=arg[2]? arg[2][139] : 0;
  if (res[2]!=0) res[2][137]=a5;
  if (res[2]!=0) res[2][138]=a3;
  if (res[2]!=0) res[2][139]=a3;
  a5=arg[2]? arg[2][143] : 0;
  a6=(a2*a5);
  a7=arg[2]? arg[2][142] : 0;
  a4=(a1*a7);
  a4=(a0*a4);
  a6=(a6-a4);
  if (res[2]!=0) res[2][140]=a6;
  a5=(a1*a5);
  a7=(a2*a7);
  a7=(a0*a7);
  a5=(a5+a7);
  if (res[2]!=0) res[2][141]=a5;
  a5=arg[2]? arg[2][144] : 0;
  if (res[2]!=0) res[2][142]=a5;
  a5=arg[2]? arg[2][145] : 0;
  if (res[2]!=0) res[2][143]=a5;
  a5=arg[2]? arg[2][146] : 0;
  if (res[2]!=0) res[2][144]=a5;
  if (res[2]!=0) res[2][145]=a3;
  if (res[2]!=0) res[2][146]=a3;
  a5=arg[2]? arg[2][150] : 0;
  a7=(a2*a5);
  a6=arg[2]? arg[2][149] : 0;
  a4=(a1*a6);
  a4=(a0*a4);
  a7=(a7-a4);
  if (res[2]!=0) res[2][147]=a7;
  a1=(a1*a5);
  a2=(a2*a6);
  a0=(a0*a2);
  a1=(a1+a0);
  if (res[2]!=0) res[2][148]=a1;
  a1=arg[2]? arg[2][151] : 0;
  if (res[2]!=0) res[2][149]=a1;
  a1=arg[2]? arg[2][152] : 0;
  if (res[2]!=0) res[2][150]=a1;
  a1=arg[2]? arg[2][153] : 0;
  if (res[2]!=0) res[2][151]=a1;
  if (res[2]!=0) res[2][152]=a3;
  if (res[2]!=0) res[2][153]=a3;
  return 0;
}

CASADI_SYMBOL_EXPORT int ddmr_expl_vde_forw(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ddmr_expl_vde_forw_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ddmr_expl_vde_forw_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ddmr_expl_vde_forw_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ddmr_expl_vde_forw_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ddmr_expl_vde_forw_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ddmr_expl_vde_forw_incref(void) {
}

CASADI_SYMBOL_EXPORT void ddmr_expl_vde_forw_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ddmr_expl_vde_forw_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int ddmr_expl_vde_forw_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real ddmr_expl_vde_forw_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ddmr_expl_vde_forw_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ddmr_expl_vde_forw_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ddmr_expl_vde_forw_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    case 4: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ddmr_expl_vde_forw_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ddmr_expl_vde_forw_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int ddmr_expl_vde_forw_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
